
export const two = [
  
["right ", "오른쪽" ],
["left", "왼쪽" ],
["ဖြစ်ပါတယ်", "돼요" ],
["colour", "색깔" ],
["used/second-handed", "중고" ],
["စျေးပေါစွာ", "싸게" ],
["rehab center", "재활용센터" ],
["rehabilitation/rehab", "재활" ],
["dragon/use", "용" ],
["realestate dealer", "부동산중개소" ],
["unshakeable", "부동" ],
["every month/monthly", "매달/매월" ],
["every week", "매주" ],
["every year", "매년" ],
["every dag", "매일" ],
["all", "모두/다" ],
["အဲဒီနေ့ကို", "그날을" ],
["fine/penalty", "벌금" ],
["monthly salary", "월급" ],
["tax", "세금" ],


["security deposit/guarantee money", "보증금" ],
["different/other", "다른" ],
["monthly payment (rent)", "월세" ],
["lump sum of deposit (for years/no repaid)", "전세" ],
["transportation ecpense/ကားခ", "차비" ],
["theater", "극장" ],
["is free of charge", "무료이다" ],
["free", "무료/공짜" ],
["သွားပြီးပြန်လာခဲ့ပါတယ်", "갔다왔어요" ],
["inquire", "알아보다/문의하다" ],
["rest", "쉬다" ],
["easy", "쉽다" ],
["difficult", "어렵다" ],
["finding employment/getting a job", "취업" ],
["education", "교육" ],
["အလုပ်ဝင်ပညာပေးဌာန ", "취업교육기관" ],
["employment/hiring", "고용" ],
["အလုပ်ခန့်စင်တာ", "고용안정센터" ],
["documents/paperwork", "서류" ],
["copy", "복사하다" ],

["how much", "몇" ],
["instant noodle", "라면" ],
["ကြာဇံ", "국수" ],
["city hall/municipal office building", "시청" ],
["front", "앞" ],
["behind", "뒤" ],
["under", "아래/밑" ],
["next to/beside", "옆" ],
["transportation card (to pay)", "교통카드" ],
["end of the month (days)", "월말" ],
["end of the year", "연말" ],
["end of semester/finals", "기말" ],
["savkng/savings", "저금" ],
["stand/build/establish/set", "세우다" ],
["park car", "차를세우다" ],
["lay out plan", "계획을세우다" ],
["plan", "계확" ],
["order (restaurant)", "주문" ],
["take order", "주문하다" ],
["tell someone to do something/make/cause", "시키다" ],

["ဘယ်လိုလုပ်မလဲ ", "어떡하죠" ],
["lost", "잃다" ],
["lost", "잃어버리다" ],
["lost", "분실하다" ],
["lost things center", "분실물센터" ],
["lonh", "길다" ],
["usually/normally", "보통" ],
["blocked/clogged", "막이다" ],
["overpass/footbridge", "육교" ],
["undergrohnd tunnel", "지하도" ],
["crosswalk/zebra crossing", "횡단보도" ],
["how", "어떤" ],
["occupation/profession", "직업" ],
["about/around", "쯤/정도" ],
["employee", "직원" ],
["addrees", "주소" ],
["reading", "독서" ],
["character/personality", "성격" ],
["work/job", "업무" ],
["bussiness/work", "사업" ],
["place of bussiness", "사업장" ],
["give welfare", "복지하다" ],
["welfare center", "복지센터" ],


["consult/counsel ", "상담" ],
["consulting center", "상담센터" ],
["korean language teaching class", "한국어교육기관" ],
["eye clinic", "안과" ],
["internal clinic", "내과" ],
["dental clinic", "치과" ],
["external clinic", "외과" ],
["calcutate/estimate cost", "계산하다" ],
["dollar", "달러" ],
["evening", "저녁" ],
["alcolohilic beverage", "술" ],
["company dinner", "회식" ],
["going to work", "출근" ],
["leaving work", "퇴근" ],
["ခဏလေးပါ", "잠깐만요" ],
["alittle", "조금/좀" ],
["red", "빨간" ],
["ဖြစ်ပါတယ်", "이에요" ],
["aspect/facet/direction/way", "방면" ],
["have/bring", "가지다" ],

["ယူသွားသည်", "가져가다" ],
["ဆင်းသွားသည်", "내려가다" ],
["ခေါ်ဆောင်သွားသည်", "데려가다" ],
["go up/climb", "올라가다" ],
["train station", "역" ],
["မြေထွန်သည်", "밭을갈다" ],
["2လိုင်း", "2호선" ],
["transfer/change transportation", "갈아타다" ],
["come back/return", "돌아오다" ],
["department manager/team-leader", "과장님" ],
["seat/place", "자리" ],
["မရှိပါ", "안계신데요" ],
["memo", "메모" ],
["ချန်ထားပေးရမလား", "남겨드릴까요" ],
["leave behind", "남기다" ],
["later", "나중에" ],
["one more", "다시" ],
["cook rice", "밥을짓다" ],
["do farming", "논을짓다" ],
["degree/extent", "정도" ],

["arrive", "도착하다" ],
["already", "벌써" ],
["daughtet", "딸" ],
["son", "아들" ],
["get a job", "취직하다" ],
["seek/look for/ကယ်ဆယ်", "구하다" ],
["hello", "여보세요" ],
["house", "댁/집" ],
["ဖြစ်သည်", "이다" ],
["cut/trim (price)", "깎다" ],
["finish", "끝내다" ],
["first/in advance", "먼저" ],
["အရင်ပြန်နှင့်ပါ", "먼저 들어가세요" ],
["gas fee", "가스비" ],
["ထွက်လာသည် (cost)", "나오다" ],
["almost/neay", "거의" ],
["food waste", "음식물" ],
["environment", "환경" ],

["pollution", "오염" ],
["serious/grave", "심각하다" ],
["serious", "심하다" ],
["bored", "심심하다" ],
["lazy/indolent", "게으르다" ],
["platform (train station. airport)", "승강장" ],
["between/relationship/gap", "사이" ],
["fall/left out/remove", "빠지다" ],
["worry", "염려" ],
["fax", "팩스" ],
["country number", "국가번호" ],
["region number", "지역번호" ],
["type", "누르다" ],
["tear apart", "찢다" ],
["farry", "통근" ],
["erase", "지우다" ],
["depart", "떠너다" ],
["miss (bus)", "놓치다" ],
["push", "밀다" ],
["push", "당기다" ],

["long holiday", "연휴" ],
["မတွေ့ရတာကြာသော", "오래만에" ],
["သွားပြီးပြန်လာသည်", "다녀오다" ],


/*


["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
*/
  ]