const rawIntoReady = (array) => {
  const newarray = []
  array.map(item => {
    const obj = {
      eng : item[0],
      korean: item[1],
    }
   newarray.push(obj)
  })
  return newarray
}




  

const raw = [
  ['singer', '가수' ],
  ['meat', '고기' ],
  ['shoe', '구두' ],
  [ 'nation', '나라' ],
  ['wood/tree',  '나무' ],
  ['leg/bridge', '다리' ],
  ['radio', '라디오' ],
  ['head/hair', '머리' ],
  ['banana', '바나나' ],
  ['pant', '바지' ],
  ['cow', '소' ],
  ['infant', '아기' ],
  ['mother', '어머니' ],
  ['map', '지도' ],
  ['hat', '모자' ],
  ['father', '아버지' ],
  ['waist', '허리' ],
  ['underground', '지하' ],
  ['baseball', '야구' ],
  ['coconut tree', '야자수' ],
  ['girl', '여자' ],
  ['rice', '벼' ],
  ['tongue', '혀' ],
  ['yoga', '요가' ],
  ['teacher', '교사' ],
  ['professor', '교수' ],
  ['glass', '유리' ],
  ['tissue', '휴지' ],
  ['milk', '우유' ],
  ['card', '카드' ],
  ['nose', '코' ],
  ['height', '키' ],
  ['ostrich', '타조' ],
  ['tomato', '토마토' ],
  ['matador', '투우사' ],
  ['fly', '파리' ],
  ['grapes', '포도' ],
  ['stamp', '우표' ],
  ['car/tea', '차' ],
  ['skirt', '치마' ],
  ['pepper', '고추' ],
  ['coffee', '커피' ],
  ['coat', '코트' ],
  ['train ticket', '기차표' ],
  ['furniture', '가구' ],
  ['teeth', '이/치아' ],
  ['iron (cloth)', '다리미' ],
  ['fertilizer', '비료' ],
  ['fold ladder', '사다리' ],
  ['rain', '비' ],
  ['syringe', '주사기' ],
  ['spoon and chopstick', '수저' ],
  ['screwdriver', '드라이버' ],
  ['abrasive paper', '사포' ],
  ['knocking', '노크' ],
  ['ticket', '표' ],
  ['sofa', '소파' ],
  ['soap', '비누' ],
  ['t-shirt', '티셔츠' ],
  ['pipe', '호스' ],
  ['check ticket', '수표' ],
  ['train', '기차' ],
  ['motorcycle', '오토바이' ],
  ['bus', '버스' ],
  ['mask', '마스크' ],
  ['petrol shop', '주유소' ],
  ['duck', '오리' ],
  ['animal food', '사료' ],
  ['cup with handle', '바가지' ],
  ['protection accessories',  '보호구' ],
  ['cutting board', '도마' ],
  ['hoe', '호미' ],
  ['apartment', '아파트' ],
  ['I', '나'],
  ['you','너'],
  ['parcel', '소포'],
  ['mosquito', '모기'],
  ['cucumber', '오이'],
  ['garage', '차고'],
  ['jeogori', '저고리'],
  ['magpie', '까치'],
  ['tail', '꼬리'],
  ['elephant', '코끼리'],
  ['hair band', '머리띠'],
  ['root', '뿌리'],
  ['bone', '뼈'],
  ['father', '아빠'],
  ['ulaygee','아저씨'],
  ['fake', '가짜'],
  ['belt', '허리띠'],
  ['axe', '도끼'],
  ['brother', '오빠'],
  ['rabbit', '토끼'],
  ['also', '또'],
  ['shoulder','어깨'],
  ['ant', '개미'],
  ['boat,pear,stomach', '배'],
  ['bird,new', '새'],
  ['sun,sea', '해'],
  ['crab', '게'],
  ['swing', '그네'],
  ['camera', '카메라'],
  ['watch', '시계'],
  ['dog', '개'],
  ['song', '노래'],
  ['trash', '쓰레기'],
  ['shop', '가게'],
  ['tape', '테이프'],
  ['fork lift', '지게차'],
  ['vegetable', '채소'],
  ['cash', '지폐'],
  ['machine', '기계'],
  ['staging,falsework,fat', '비계'],
  ['earth', '세계'],
  ['pillow', '베개'],
  ['yesterday', '어제'],
  ['apple','사과'],
  ['snack', '과자'],
  ['pig', '돼지'],
  ['fire extinguisher', '소화기'],
  ['sweater', '스웨터'],
  ['waiter', '웨이터'],
  ['beef', '쇠고기,소고기'],
  ['company', '회사'],
  ['ear', '귀'],
  ['mouse', '쥐'],
  ['scissor', '가위'],
  ['doctor', '의사'],
  ['chair', '의자'],
  ['brain', '두뇌'],
  ['book', '책'],
  ['taxi', '택시'],
  ['crop', '곡식'],
  ['highway bus', '고속버스'],
  ['soup', '국'],
  ['pharmacy', '약국'],
  ['post office', '우체국'],
  ['pet', '가축'],
  ['washing machine', '세탁기'],
  ['copier', '복사기'],
  ['umbrella', '우산'],
  ['newspaper', '신문'],
  ['bicycle', '자전거'],
  ['calculator', '계산기'],
  ['money', '돈'],
  ['cart', '손수레'],
  ['leaflet', '전단지'],
  ['water spray', '분무기'],
  ['rope', '끈'],
  ['passport', '여권'],
  ['reaper', '낫'],
  ['iron,pond', '못'],
  ['screw', '나사못'],
  ['shirt', '옷'],
  ['spoon', '숟가락'],
  ['bowl', '그릇'],
  ['flower', '꽃'],
  ['farm', '밭'],
  ['bookshelf', '책꽂이'],
  ['chopstick', '젓가락'],
  ['go', '가다'],
  ['go out', '나가다'],
  ['share', '나누다'],
  ['attend', '다니다'],
  ['different', '다르다'],
  ['wait', '기다리다'],
  ["don't know ", '모르다'],
  ['paint', '바르다'],
  ['shout,sing,full', '부르다'],
  ['buy', '사다'],
  ['win', '이기다'],
  ['lose', '지다'],
  ['sleep', '자다'],
  ['kick', '차다'],
  ['beat', '치다'],
  ['teach', '가르치다'],
  ['big', '크다'],
  ['ride', '타다'],
  ['dig', '파다'],
  ['do', '하다'],
  ['peel', '까다'],
  ['put on glasses', '끼다'],
  ['turn off switch', '끄다'],
  ['sun rise', '뜨다'],
  ['pluck fruit', '따다'],
  ['busy', '바쁘다'],
  ['fast', '빠르다'],
  ['cheap', '싸다'],
  ['expensive', '비싸다'],
  ['poke with fork', '찌르다'],
  ['measure', '재다'],
  ['pay tax', '내다'],
  ['send', '보내다'],
  ['speak', '얘기하다'],
  ['wash', '세수하다'],
  ['wash car', '세차하다'],
  ['beautiful', '예쁘다'],
  ['apologize', '사과하다'],
  ['do too much', '과로하다'],
  ['memorize', '외우다'],
  ['rice bag','쌀자루'],
  ['calender','달력'],
  ['blanket','이불'],
  ['net','그물'],
  ['truck','화물차'],
  ['pencil','연필'],
  ['brick','벽돌'],
  ['rebar','철근'],
  ['hemp rope','밧줄'],
  ['underground train','지하철'],
  ['sew','꿰매다'],
  ['run','뛰다'],
  ['drunk','취하다'],
  ['hold meeting','회의하다'],
  ['prebuy','예먜하다'],
  ['wipe(teeth,car,glass)','닦다'],
  ['hammer(v)','박다'],
  ['late(work,school)','지각하다'],
  ['sign the contract','계약하다'],
  ['eat','먹다/드시다'],
  ['meet','만나다'],
  ['many','많다'],
  ['sit','앉다'],
  ['bring','운반하다,나르다'],
  ['drive','운전하다'],
  ['human', '사람'],
  ['boy', '남자'],
  ['computer', '컴표터'],
  ['book store', '서점'],
  ['locker', '보관함'],
  ['bed', '침대'],
  ['pajama', '잠옷'],
  ['cost', '요금'],
  ['cigeratte', '담배'],
  ['drawer', '서류함'],
  ['mall', '백화점'],
  ['ahtettar', '합판'],
  ['purse', '지갑'],
  ['cooked rice', '밥'],
  ['house', '집'],
  ['korean restaurant', '한식집'],
  ['notebook', '수첩'],
  ['electric saw', '전기톱'],
  ['price', '값/가격'],
  ['new housing celebration', '집들이'],
  ['interview', '면접'],
  ['bag', '가방'],
  ['stamp', '도장'],
  ['long neck shoe', '장화'],
  ['small box', '상자'],
  ['airplane', '비행기'],
  ['fan', '선풍기'],
  ['htawlargyi', '경운기'],
  ['sport shoe', '운동화'],
  ['payphone', '공중전화'],
  ['fridge', '냉장고'],
  ['teacher', '선생님'],
  ['name', '이름'],
  ['seoul', '서울'],
  ['capital', '수도'],
  ['korea', '한국'],
  ['america', '미국'],
  ['brother', '형'],
  ['short', '짧다'],
  ['dictionary', '사전'],
  ['library', '도서관'],
  ['boss', '사장님'],
  ['sell', '팔다'],
  ['movie', '영화'],
  ['clinic', '보건소'],
  ['vaccine', '예방주사'],
  ['baby', '아이'],
  ['near', '근처'],
  ['convenience store', '편의점'],
  ['go in', '들어가다'],
  ['plant(v)', '심다'],
  ['room', '방'],
  ['clean(v)', '정소하다'],
  ['korean language', '한국어'],
  ['study', '공부하다'],
  ['good', '좋다'],
  ['put', '놓다'],
  ['wash(hand/vegetable)', '씻다'],
  ['put on the vehicle', '싣다'],
  ['is(shi)', '있다,계시다'],
  ['know', '알다'],
  ['stay', '살다'],
  ['open(door,shop)', '열다'],
  ['far', '멀다'],
  ['make money', '벌다'],
  ['wash hair', '감다'],
  ['surpass', '넘다'],
  ['fall down', '넘어지다'],
  ['transfer', '옮기다'],
  ['breath', '숨쉬다'],
  ['empty', '없다'],
  ['heavy', '무겁다'],
  ['light', '가볍다'],
  ['scared', '무섭다'],
  ['dirty','더럽다'],
  ['love', '사랑하다'],
  ['healthy', '건강하다'],
  ['broke(machine)', '고장나다'],
  ['exercise', '운동하다'],
  ['go trip', '여행가다'],
  ['day', '요일/날짜'],
  ['monday', '월요일'],
  ['tuesday', '화요일'],
  ['wednesday', '수요일'],
  ['thursday', '목요일'],
  ['friday', '금요일'],
  ['saturday', '토요일'],
  ['sunday', '일요일'],
  ['the whole week', '일주일'],
  ['weekdays', '주중/평일'],
  ['weekends', '주말'],
  ['this place', '이곳/여기'],
  ['that place', '그곳/거기'],
  ['ho there', '저곳/저기'],
  ['this thing', '이것/이거'],
  ['that thing', '그것/그거'],
  ['ho thing', '저것/저거'],
  ['this person', '이분/이사람'],
  ['that person', '그분/그사람'],
  ['ho person', '저분/저사람'],
  ['day before yesterday', '그저께'],
  ['yesterday', '어제'],
  ['today', '오늘'],
  ['tomorrow', '내일'],
  ['aftermorrow', '모레'],
  ['day after aftermorrow', '글피'],
  ['last week', '지난주'],
  ['last month', '지난달'],
  ['last year', '지난해/작년'],
  ['this week', '이번주'],
  ['this month', '이번달'],
  ['this year', '이번해/올해'],
  ['next week', '다음주'],
  ['next month', '다음달'],
  ['next year', '다음해/내년'],
  ['1', '일'],
  ['2', '이'],
  ['3', '삼'],
  ['4', '사'],
  ['5', '오'],
  ['6', '육'],
  ['7', '칠'],
  ['8', '팔'],
  ['9', '구'],
  ['10', '십'],
  ['100', '백'],
  ['1000', '천'],
  ['10000', '만'],
  ['10000,0000', '억'],
  ['16', '십육(심뉵)'],
  
  ['birthday','생일/생신'],
  ['together','같이'],
  ['bread','빵'],
  ['hospital','병원'],
  ['market','시장'],
  ['fruit','과일'],
  ['in town','시내'],
  ['look','보다'],
  ['treatment','치료'],
  ['accept','받다'],
  
  ['outside','밖/바깥'],
  ['little brother','남동생'],
  ['little sister','여동생'],
  ['baby dog','강아지'],
  ['inside','안'],
  ['right/injected','맞다'],
  ['desk','책상'],
  ['cake','케이크'],
  ['up','위'],
  ['book(balar)','공책'],
  ['big sister','누나'],
  ['make','만들다'],
  ['park','공원'],
  ['walk (for fresh air)','산책하다'],
  ['like','좋아하다'],
  ['class','학원'],
  ['that student','그학생'],
  ['gimchi','김치'],
  ['lately','요즘'],
  
  ['birthplace','고향'],
  ['food','음식'],
  ['what','뭐/무엇/무슨'],
  ['absolutely','꼭/바드시'],
  ['safety belt','안전벨트'],
  ['tie/hang(on self)','매다'],
  ['door','문'],
  ['close (shop/door)','닫다'],
  ['cutting job','절단작업'],
  ['safety glasses','보안경'],
  ['hammer','망치'],
  ['ajumma','아줌마'],
  ['ballpen','볼펜'],
  ['afternoon','점심'],
  ['pool','수영장'],
  ['write letter','편지를쓰다'],
  ['paper','종이'],
  ['cut','자르다'],
  ['sugar','설탕'],
  ['meteorology','날씨'],
  ['hiking','등산'],
  ['factory','공장'],
  ['rice tote','비빔밥'],
  ['ill','아프다'],
  ['need','필요하다'],
  ['glasses','안경'],
  ['work(v)','일을하다'],
  ['photograph','사진'],
  ['swimming','수영'],
  ['age','나이/연세'],
  
  ['attend school abroad','유학하다'],
  ['take photo','찍다'],
  ['marry','결혼하다'],
  ['move (to another house)','이사하다'],
  ['help','도와주다'],
  ['တွေ','들'],
  ['school','학교'],
  ['abroad','외국'],
  ['use/write/bitter','쓰다'],
  ['use','사용하다'],
  
  ['1','하나/한'],
  ['2','둘/두'],
  ['3','셋/세'],
  ['4','넷/네'],
  ['5','다섯'],
  ['6','여섯'],
  ['7','일곱'],
  ['8','여덟'],
  ['9','아홉'],
  ['10','열'],
  ['20','스무/스물'],
  ['30','서른'],
  ['40','마흔'],
  ['50','쉰'],
  ['60','예순'],
  ['70','일흔'],
  ['80','여든'],
  ['90','아흔'],
  
  ['ဘူး (parcel)', '갑'],
  ['လုံး (bowl)', '그릇'],
  ['ကောင် (animal)','마리'],
  ['ထည်  (cloth)','벌'],
  ['နှစ်  (age)','살'],
  ['နာရီ  (time)','시'],
  ['ခွက်  (coffee)','잔'],
  ['လုံး  (house/building)','채'],
  ['ရွက်  (paper)','장'],
  ['စုံ/ရံ (shoe/sock)','켤레'],
  ['အုပ် (book)','권'],
  ['ချောင်း (pencil/ruler)','자루'],
  ['ခု () /လုံး (apple)','개'],
  ['စီး (ship)','척'],
  ['ပွင့် (flower)','송이'],
  ['လုံး (house)','동'],
  ['ယောက် (person)','분/명'],
  ['ယောက်စာ (per person)','인분'],
  ['ပုလင်း (bottle)','병'],
  ['လုံး (rice)','공기'],
  ['ဘူး (oil) /လုံး (watermelon)','통'],
  ['ကြာချိန်','시간'],
  ['တောင်း (basket)','바구니'],
  ['အိတ် (envelope)','봉지'],
  ['ဘူး/သေတ္တာ',"박스"],
  ['စီး (vehicle) /လုံး (machine)','대'],
  ['အိတ် (floor/concrete powder)','포대'],
  ['ပင် (tree)','그루'],
  
  
  ['taste','맛'],
  ['sweet','달다'],
  ['sour','시다'],
  ['spicy','맵다'],
  ['salty','짜다'],
  ['light(taste)','싱겁다'],
  ['cold(food)','차다/차갑다'],
  ['hot(food)','뜨겁다'],
  ['delicious','맛있다'],
  ['not delicious','맛없다(마덥다)'],
  
  ['come','오다'],
  ['shallow','얕다'],
  ['thin','얇다'],
  ['stand up','일어서다'],
  ['put in','넣다'],
  ['cross','건너다'],
  
  ["turn on switch","켜다"],
  ["spread","펴다"],
  ["used up","지내다"],
  ["spit","뱉다"],
  ["exchange","바꾸다"],
  ["learn","배우다"],
  ["die","죽다"],
  ["start","시작하다"],
  ["swim","수영하다"],
  ["sad","슬프다"],
  ["happy","기쁘다"],
  ["late","늦다"],
  
  ["old",""],
  ["read out",""],
  
  ["drink","마시다"],
  ["read",""],
  
  ["believe","믿다"],
  ["shout","부르다"],
  ["walk","걷다"],
  ["understand (oh i get it)","깨닫다"],
  ["hear/listen","듣다"],
  ["accept2","얻다"],
  ["ask/bury","묻다"],
  ["draw the line","긋다"],
  ["get something back","낫다"],
  
  ["pour","붓다"],
  
  ["connect","잇다"],
  ["build","짓다"],
  ["mix","젓다"],
  ["strip off","벗다"],
  ["comb","빗다"],
  
  ["chew","씹다"],
  ["choose/pull out","뽑다"],
  ["carry on ones back","업다"],
  ["wear","입다"],
  ["catch/grab","잡다"],
  ["fold","접다"],
  ["narrow","좁다"],
  ["pick up","집다"],
  
  ["how","어떻다"],
  ["red","빨갛다"],
  ["blue","파랗다"],
  ["yellow","노랗다"],
  ["black","까맣다"],
  ["white","하얗다"],
  ["hot","덥다"],
  ["thank","고맙다"],
  ["help","돕다"],
  ["soft","곱다"],
  
  ["blank","빈칸"],
  ["the end","가장/제일"],
  ["right","맞다/알맞다"],
  
  ["fine (im fine)",""],
  
  ["seem","보이다"],
  ["get cold","감기에걸리다"],
  ["get high temperature ","열이나다"],
  ["cough","기침이나다"],
  ["illness","열"],
  ["getting cold(ill)","감기"],
  ["neck","목"],
  ["medicine","약"],
  ["county office","구청"],
  ["korea tongue","한국말"],
  ["during","동안"],
  ["month span","개월"],
  ["near","근처/가까이"],
  ["coughing","기침"],
  ["bank","은행"],
  ["cinema","영화관"],
  ["tourism guide centre","관광안내센터"],
  ["indonesia","인도네시아"],
  ["name","이름/성함"],
  ["hobby","취미"],
  ["family","가죽"],
  ["friend","친구"],
  ["go pick somebody up(receive)","마중가다"],
  ["harbour","항구"],
  ["airport","공항"],
  ["watermelon","수박"],
  ["usually(most of the time)","주로"],
  ["(bus )stop","정류장"],
  ["very","너무/아주"],
  ["thing","물건"],
  
  ]
  
const Grammer = [
  ["၏/ရဲ့","의"],
  //grammer
  ['ဖြစ်ပါတယ်','N+입니다'],
  ['ဖြစ်ပါသလား','N+입니까'],
  ['ကတော့/သော','N+은/는'],
  ['က','N+이/가'],
  ['ပါတယ်','V+.ㅂ니다/습니다'],
  ['ပါသလား','V+.ㅂ니까/습니까'],
  ['ကို','N+을/를'],
  ['ကို','N+에(가다,오다)'],
  ['မှာ','N+에서'],
  ['မှာ','N+에(있다,계시다,없다,살다,많다,앉다)'],
  ['and','N+와/과'],
  ['and','N+하고'],
  ['and','N+랑/이랑'],
  ['and','N+및'],
  ['ကြမလား/ရမလား','V+을까요/.ㄹ까요'],
  ['မဘူး','V+지못합니다'],
  ['မဘူး','V+지않습니다'],
  ['ချင်တယ်','V+고싶습니다'],
  ['ပါ','V+세요/으세요'],
  ['ပါ','V+십시오/으십시오'],
  ['နေပါတယ်/ထားပါတယ်','V+고있습니다'],
  ['မလို့ပါ','V+려고합니다/으려고합니다'],
  ['ရင်/လျှင်','V+면/으면'],
  ['ချင်ရင်','V+려면/으려면'],
  ['ရင်းနဲ့','V+면서/으면서'],
  ['သောအခါ/တဲ့အခါ','V+을때/.ㄹ때'],
  ['လည်းပဲ','N+도'],
  ['ပြီးတော့','V+고'],
  ['အစ','N+부터'],
  ['အထိ','N+까지'],
  
  ]
  
  
  
export const words = rawIntoReady(raw)
