const rawIntoReady = (array) => {
  const newarray = []
  array.map(item => {
    const obj = {
      eng : item[0],
      korean: item[1],
    }
   newarray.push(obj)
  })
  return newarray
}


 

  

const raw = [
  ['singer', '가수' ],
  ['meat', '고기' ],
  ['shoe', '구두' ],
  [ 'nation', '나라' ],
  ['wood/tree',  '나무' ],
  ['leg/bridge', '다리' ],
  ['radio', '라디오' ],
  ['head/hair', '머리' ],
  ['banana', '바나나' ],
  ['pant', '바지' ],
  ['cow', '소' ],
  ['infant', '아기' ],
  ['mother', '어머니' ],
  ['map', '지도' ],
  ['hat', '모자' ],
  ['father', '아버지' ],
  ['waist', '허리' ],
  ['underground', '지하' ],
  ['baseball', '야구' ],
  ['coconut tree', '야자수' ],
  ['girl', '여자' ],
  ['rice', '벼' ],
  ['tongue', '혀' ],
  ['yoga', '요가' ],
  ['teacher', '교사' ],
  ['professor', '교수' ],
  ['glass', '유리' ],
  ['tissue', '휴지' ],
  ['milk', '우유' ],
  ['card', '카드' ],
  ['nose', '코' ],
  ['height', '키' ],
  ['ostrich', '타조' ],
  ['tomato', '토마토' ],
  ['matador', '투우사' ],
  ['fly', '파리' ],
  ['grapes', '포도' ],
  ['stamp', '우표' ],
  ['car/tea', '차' ],
  ['skirt', '치마' ],
  ['pepper', '고추' ],
  ['coffee', '커피' ],
  ['coat', '코트' ],
  ['train ticket', '기차표' ],
  ['furniture', '가구' ],
  ['teeth', '이/치아' ],
  ['iron (cloth)', '다리미' ],
  ['fertilizer', '비료' ],
  ['fold ladder', '사다리' ],
  ['rain', '비' ],
  ['syringe', '주사기' ],
  ['spoon and chopstick', '수저' ],
  ['screwdriver', '드라이버' ],
  ['abrasive paper', '사포' ],
  ['knocking', '노크' ],
  ['ticket', '표' ],
  ['sofa', '소파' ],
  ['soap', '비누' ],
  ['t-shirt', '티셔츠' ],
  ['pipe', '호스' ],
  ['check ticket', '수표' ],
  ['train', '기차' ],
  ['motorcycle', '오토바이' ],
  ['bus', '버스' ],
  ['mask', '마스크' ],
  ['petrol shop', '주유소' ],
  ['duck', '오리' ],
  ['animal food', '사료' ],
  ['cup with handle', '바가지' ],
  ['protection accessories',  '보호구' ],
  ['cutting board', '도마' ],
  ['hoe', '호미' ],
  ['apartment', '아파트' ],
  ['I', '나'],
  ['you','너'],
  ['parcel', '소포'],
  ['mosquito', '모기'],
  ['cucumber', '오이'],
  ['garage', '차고'],
  ['jeogori', '저고리'],
  ['magpie', '까치'],
  ['tail', '꼬리'],
  ['elephant', '코끼리'],
  ['hair band', '머리띠'],
  ['root', '뿌리'],
  ['bone', '뼈'],
  ['father', '아빠'],
  ['ulaygee','아저씨'],
  ['fake', '가짜'],
  ['belt', '허리띠'],
  ['axe', '도끼'],
  ['brother', '오빠'],
  ['rabbit', '토끼'],
  ['also', '또'],
  ['shoulder','어깨'],
  ['ant', '개미'],
  ['boat,pear,stomach', '배'],
  ['bird,new', '새'],
  ['sun,sea', '해'],
  ['crab', '게'],
  ['swing', '그네'],
  ['camera', '카메라'],
  ['watch', '시계'],
  ['dog', '개'],
  ['song', '노래'],
  ['trash', '쓰레기'],
  ['shop', '가게'],
  ['tape', '테이프'],
  ['fork lift', '지게차'],
  ['vegetable (green)', '채소'],
  ['cash', '지폐'],
  ['machine', '기계'],
  ['staging,falsework,fat', '비계'],
  ['earth', '세계'],
  ['pillow', '베개'],
  ['yesterday', '어제'],
  ['apple','사과'],
  ['snack', '과자'],
  ['pig', '돼지'],
  ['fire extinguisher', '소화기'],
  ['sweater', '스웨터'],
  ['waiter', '웨이터'],
  ['beef', '쇠고기/소고기'],
  ['company', '회사'],
  ['ear', '귀'],
  ['mouse', '쥐'],
  ['scissor', '가위'],
  ['doctor', '의사'],
  ['chair', '의자'],
  ['brain', '두뇌'],
  ['book', '책'],
  ['taxi', '택시'],
  ['crop', '곡식'],
  ['highway bus', '고속버스'],
  ['soup', '국'],
  ['pharmacy', '약국'],
  ['post office', '우체국'],
  ['pet', '가축'],
  ['washing machine', '세탁기'],
  ['copier', '복사기'],
  ['umbrella', '우산'],
  ['newspaper', '신문'],
  ['bicycle', '자전거'],
  ['calculator', '계산기'],
  ['money', '돈'],
  ['cart', '손수레'],
  ['leaflet', '전단지'],
  ['water spray', '분무기'],
  ['rope', '끈'],
  ['passport', '여권'],
  ['reaper', '낫'],
  ['iron,pond', '못'],
  ['screw', '나사못'],
  ['shirt', '옷'],
  ['spoon', '숟가락'],
  ['bowl', '그릇'],
  ['flower', '꽃'],
  ['farm', '밭'],
  ['bookshelf', '책꽂이'],
  ['chopstick', '젓가락'],
  ['go', '가다'],
  ['go out', '나가다'],
  ['share', '나누다'],
  ['attend', '다니다'],
  ['different', '다르다'],
  ['wait', '기다리다'],
  ["don't know ", '모르다'],
  ['paint', '바르다'],
  ['shout,sing,full', '부르다'],
  ['buy', '사다'],
  ['win', '이기다'],
  ['lose', '지다'],
  ['sleep', '자다'],
  ['kick', '차다'],
  ['beat', '치다'],
  ['teach', '가르치다'],
  ['big', '크다'],
  ['ride', '타다'],
  ['dig', '파다'],
  ['do', '하다'],
  ['peel', '까다'],
  ['put on (glasses/glove)', '끼다'],
  ['turn off switch', '끄다'],
  ['sun rise', '뜨다'],
  ['pluck fruit', '따다'],
  ['busy', '바쁘다'],
  ['fast', '빠르다'],
  ['cheap', '싸다'],
  ['expensive', '비싸다'],
  ['poke with fork', '찌르다'],
  ['measure', '재다'],
  ['pay tax', '내다'],
  ['send', '보내다'],
  ['speak', '얘기하다'],
  ['wash', '세수하다'],
  ['wash car', '세차하다'],
  ['beautiful', '예쁘다'],
  ['apologize', '사과하다'],
  ['do too much', '과로하다'],
  ['memorize', '외우다'],
  ['rice bag','쌀자루'],
  ['calender','달력'],
  ['blanket','이불'],
  ['net','그물'],
  ['truck','화물차'],
  ['pencil','연필'],
  ['brick','벽돌'],
  ['rebar','철근'],
  ['hemp rope','밧줄'],
  ['underground train','지하철'],
  ['sew','꿰매다'],
  ['run','뛰다'],
  ['drunk','취하다'],
  ['hold meeting','회의하다'],
  ['prebuy','예먜하다'],
  ['wipe(teeth,car,glass)','닦다'],
  ['hammer(v)','박다'],
  ['late(work,school)','지각하다'],
  ['sign the contract','계약하다'],
  ['eat','먹다/드시다'],
  ['meet','만나다'],
  ['many','많다'],
  ['sit','앉다'],
  ['bring','운반하다/나르다'],
  ['drive','운전하다'],
  ['human', '사람'],
  ['boy', '남자'],
  ['computer', '컴표터'],
  ['book store', '서점'],
  ['locker', '보관함'],
  ['bed', '침대'],
  ['pajama', '잠옷'],
  ['cost', '요금'],
  ['cigeratte', '담배'],
  ['drawer', '서류함'],
  ['mall', '백화점'],
  ['ahtettar', '합판'],
  ['purse', '지갑'],
  ['cooked rice', '밥'],
  ['house', '집'],
  ['korean restaurant', '한식집'],
  ['notebook', '수첩'],
  ['electric saw', '전기톱'],
  ['price', '값/가격'],
  ['new housing celebration', '집들이'],
  ['interview', '면접'],
  ['bag', '가방'],
  ['stamp', '도장'],
  ['long neck shoe', '장화'],
  ['small box', '상자'],
  ['airplane', '비행기'],
  ['fan', '선풍기'],
  ['htawlargyi', '경운기'],
  ['sport shoe', '운동화'],
  ['payphone', '공중전화'],
  ['fridge', '냉장고'],
  ['teacher', '선생님'],
  ['name', '이름'],
  ['seoul', '서울'],
  ['capital', '수도'],
  ['korea', '한국'],
  ['america', '미국'],
  ['brother', '형'],
  ['short', '짧다'],
  ['dictionary', '사전'],
  ['library', '도서관'],
  ['boss', '사장님'],
  ['sell', '팔다'],
  ['movie', '영화'],
  ['clinic', '보건소'],
  ['vaccine', '예방주사'],
  ['baby', '아이'],
  ['near', '근처'],
  ['convenience store', '편의점'],
  ['go in', '들어가다'],
  ['plant(v)', '심다'],
  ['room', '방'],
  ['clean(v)', '정소하다'],
  ['korean language', '한국어'],
  ['study', '공부하다'],
  ['good', '좋다'],
  ['put', '놓다'],
  ['wash(hand/vegetable)', '씻다'],
  ['load/put on the vehicle', '싣다'],
  ['is(shi)', '있다/계시다'],
  ['know', '알다'],
  ['stay', '살다'],
  ['open(door,shop)', '열다'],
  ['far', '멀다'],
  ['make money', '벌다'],
  ['wash hair', '감다'],
  ['surpass', '넘다'],
  ['fall down', '넘어지다'],
  ['transfer', '옮기다'],
  ['breath', '숨쉬다'],
  ['empty', '없다'],
  ['heavy', '무겁다'],
  ['light', '가볍다'],
  ['scared', '무섭다'],
  ['dirty','더럽다'],
  ['love', '사랑하다'],
  ['healthy', '건강하다'],
  ['broke(machine)', '고장나다'],
  ['exercise', '운동하다'],
  ['go trip', '여행가다'],
  ['day', '요일/날짜'],
  ['monday', '월요일'],
  ['tuesday', '화요일'],
  ['wednesday', '수요일'],
  ['thursday', '목요일'],
  ['friday', '금요일'],
  ['saturday', '토요일'],
  ['sunday', '일요일'],
  ['the whole week', '일주일'],
  ['weekdays', '주중/평일'],
  ['weekends', '주말'],
  ['this place', '이곳/여기'],
  ['that place', '그곳/거기'],
  ['ho there', '저곳/저기'],
  ['this thing', '이것/이거'],
  ['that thing', '그것/그거'],
  ['ho thing', '저것/저거'],
  ['this person', '이분/이사람'],
  ['that person', '그분/그사람'],
  ['ho person', '저분/저사람'],
  ['day before yesterday', '그저께'],
  ['yesterday', '어제'],
  ['today', '오늘'],
  ['tomorrow', '내일'],
  ['aftermorrow', '모레'],
  ['day after aftermorrow', '글피'],
  ['last week', '지난주'],
  ['last month', '지난달'],
  ['last year', '지난해/작년'],
  ['this week', '이번주'],
  ['this month', '이번달'],
  ['this year', '이번해/올해'],
  ['next week', '다음주'],
  ['next month', '다음달'],
  ['next year', '다음해/내년'],
  ['1', '일'],
  ['2', '이'],
  ['3', '삼'],
  ['4', '사'],
  ['5', '오'],
  ['6', '육'],
  ['7', '칠'],
  ['8', '팔'],
  ['9', '구'],
  ['10', '십'],
  ['100', '백'],
  ['1000', '천'],
  ['10000', '만'],
  ['10000,0000', '억'],
  ['16', '십육(심뉵)'],
  
  ['birthday','생일/생신'],
  ['together','같이'],
  ['bread','빵'],
  ['hospital','병원'],
  ['market','시장'],
  ['fruit','과일'],
  ['in town','시내'],
  ['look','보다'],
  ['treatment','치료'],
  ['accept','받다'],
  
  ['outside','밖/바깥'],
  ['little brother','남동생'],
  ['little sister','여동생'],
  ['baby dog','강아지'],
  ['inside','안'],
  ['right/injected','맞다'],
  ['desk','책상'],
  ['cake','케이크'],
  ['up','위'],
  ['book(balar)','공책'],
  ['big sister','누나'],
  ['make','만들다'],
  ['park','공원'],
  ['walk (for fresh air)','산책하다'],
  ['like','좋아하다'],
  ['class','학원'],
  ['that student','그학생'],
  ['gimchi','김치'],
  ['lately','요즘'],
  
  ['birthplace','고향'],
  ['food','음식'],
  ['what','뭐/무엇/무슨'],
  ['absolutely','꼭/바드시'],
  ['safety belt','안전벨트'],
  ['tie/hang(on self)','매다'],
  ['door','문'],
  ['close (shop/door)','닫다'],
  ['cutting job','절단작업'],
  ['safety glasses','보안경'],
  ['hammer','망치'],
  ['ajumma','아줌마'],
  ['ballpen','볼펜'],
  ['afternoon','점심'],
  ['pool','수영장'],
  ['write letter','편지를쓰다'],
  ['paper','종이'],
  ['cut','자르다'],
  ['sugar','설탕'],
  ['meteorology','날씨'],
  ['hiking','등산'],
  ['factory','공장'],
  ['rice tote','비빔밥'],
  ['ill','아프다'],
  ['need','필요하다'],
  ['glasses','안경'],
  ['work(v)','일을하다'],
  ['photograph','사진'],
  ['swimming','수영'],
  ['age','나이/연세'],
  
  ['attend school abroad','유학하다'],
  ['take photo','찍다'],
  ['marry','결혼하다'],
  ['move (to another house)','이사하다'],
  ['help','도와주다'],
  ['တွေ','들'],
  ['school','학교'],
  ['abroad','외국'],
  ['use/write/bitter','쓰다'],
  ['use','사용하다'],
  
  ['1','하나/한'],
  ['2','둘/두'],
  ['3','셋/세'],
  ['4','넷/네'],
  ['5','다섯'],
  ['6','여섯'],
  ['7','일곱'],
  ['8','여덟'],
  ['9','아홉'],
  ['10','열'],
  ['20','스무/스물'],
  ['30','서른'],
  ['40','마흔'],
  ['50','쉰'],
  ['60','예순'],
  ['70','일흔'],
  ['80','여든'],
  ['90','아흔'],
  
  ['ဘူး (parcel)', '갑'],
  ['လုံး (bowl)', '그릇'],
  ['ကောင် (animal)','마리'],
  ['ထည်  (cloth)','벌'],
  ['နှစ်  (age)','살'],
  ['နာရီ  (time)','시'],
  ['ခွက်  (coffee)','잔'],
  ['လုံး  (house/building)','채'],
  ['ရွက်  (paper)','장'],
  ['စုံ/ရံ (shoe/sock)','켤레'],
  ['အုပ် (book)','권'],
  ['ချောင်း (pencil/ruler)','자루'],
  ['ခု () /လုံး (apple)','개'],
  ['စီး (ship)','척'],
  ['ပွင့် (flower)','송이'],
  ['လုံး (house)','동'],
  ['ယောက် (person)','분/명'],
  ['ယောက်စာ (per person)','인분'],
  ['ပုလင်း (bottle)','병'],
  ['လုံး (rice)','공기'],
  ['ဘူး (oil) /လုံး (watermelon)','통'],
  ['ကြာချိန်','시간'],
  ['တောင်း (basket)','바구니'],
  ['အိတ် (envelope)','봉지'],
  ['ဘူး/သေတ္တာ',"박스"],
  ['စီး (vehicle) /လုံး (machine)','대'],
  ['အိတ် (floor/concrete powder)','포대'],
  ['ပင် (tree)','그루'],
  
  
  ['taste','맛'],
  ['sweet','달다'],
  ['sour','시다'],
  ['spicy','맵다'],
  ['salty','짜다'],
  ['light(taste)','싱겁다'],
  ['cold(food)','차다/차갑다'],
  ['hot(food)','뜨겁다'],
  ['delicious','맛있다/맛이있다'],
  ['not delicious','맛없다(마덥다)'],
  
  ['come','오다'],
  ['shallow','얕다'],
  ['thin','얇다'],
  ['stand up','일어서다'],
  ['put in','넣다'],
  ['cross (road)','건너다'],
  ["turn on switch","켜다"],
  ["spread","펴다"],
  ["used up/spend one's time / get along etc ","지내다"],
  ["spit","뱉다"],
  ["exchange","바꾸다"],
  ["learn","배우다"],
  ["die","죽다"],
  ["start","시작하다"],
  ["swim","수영하다"],
  ["sad","슬프다"],
  ["happy","기쁘다"],
  ["late","늦다"],
  ["old","늙다"],
  ["read out","읊다"],
  ["drink","마시다"],
  ["read","읽다"],
  ["believe","믿다"],
  ["shout","부르다"],
  ["walk","걷다"],
  ["understand (oh i get it)","깨닫다"],
  ["hear/listen","듣다"],
  ["accept","얻다"],
  ["ask/bury","묻다"],
  ["draw the line","긋다"],
  ["get something back","낫다"],
  ["pour","붓다"],
  ["connect","잇다"],
  ["build","짓다"],
  ["mix","젓다"],
  ["strip off","벗다"],
  ["comb","빗다"],
  ["chew","씹다"],
  ["choose/pull out","뽑다"],
  ["carry on ones back","업다"],
  ["wear","입다"],
  ["catch/grab","잡다"],
  ["fold","접다"],
  ["narrow","좁다"],
  ["pick up","집다"],
  
  ["how","어떻다"],
  ["red","빨갛다"],
  ["blue","파랗다"],
  ["yellow","노랗다"],
  ["black","까맣다"],
  ["white","하얗다"],
  ["hot","덥다"],
  ["thank","고맙다"],
  ["help","돕다"],
  ["soft","곱다"],
  
  ["blank","빈칸"],
  ["the most","가장/제일"],
  ["right","맞다/알맞다"],
  ["fine (im fine)","괜찮다"],
  ["seem","보이다"],
  ["get cold","감기에걸리다"],
  ["get high temperature ","열이나다"],
  ["cough","기침이나다"],
  ["illness","열"],
  ["getting cold(ill)","감기"],
  ["neck","목"],
  ["medicine","약"],
  ["county office","구청"],
  ["korea tongue","한국말"],
  ["during","동안"],
  ["month span","개월"],
  ["near","근처/가까이"],
  ["coughing","기침"],
  ["bank","은행"],
  ["cinema","영화관"],
  ["tourism guide centre","관광안내센터"],
  ["indonesia","인도네시아"],
  ["name","이름/성함"],
  ["hobby","취미"],
  ["family","가족"],
  ["friend","친구"],
  ["go pick somebody up(receive)","마중가다"],
  ["harbour","항구"],
  ["airport","공항"],
  ["watermelon","수박"],
  ["usually(most of the time)","주로"],
  ["(bus )stop","정류장"],
  ["very","너무/아주"],
  ["thing","물건"],
  
  
["knife", "칼" ],
["trash can", "쓰레기통" ],
["vanding machine", "자동판매기" ],
["atm", "자동인출기" ],
["household car", "자동차" ],
["phone", "전화기" ],
["tv", "텔레비전" ],

["bussiness card (address)", "명함" ], 
["glove", "장갑" ], 
["white shirt", "와이셔츠" ],
["student card", "학생증" ],
["employee card", "사원증" ],
["driver card", "운전면허증" ],
["health insurance card", "건강보험증" ],
["thermometer", "온도계" ],
["vacuum machine", "청소기" ],
["mirror", "거울" ],
["mailbox", "우체통" ],
["key", "열쇠" ],
["tape measure/ tapeline", "줄자" ],
["eraser", "지우개" ],
["movie ticket", "영화표" ],
["receipt (bill)", "영수증" ],
["wardrobe", "옷장" ],
["book case", "책장" ],
["sock", "양말" ],
["camera", "사진기" ],
["mobile phone", "휴대전화" ],
["laptop", "노트북컴퓨터" ],
["shovel", "삽" ],
["wire (zinc )", "철사" ],
["awl", "송곳" ],
["screw", "나사" ],

["ruler", "자" ],
["line (tape measure )", "줄" ],
["moneybag (pocket)", "주머니" ],

["sticker", "스티커" ],
["pesticide", "농약" ],
["ring (not on finger)", "고리" ],
["bag", "봉지" ],
["coolie rack", "지게" ],
["needle", "압정" ],
["brush (for painting)", "붓" ],
["light bulb", "등" ],
["apron", "앞치마" ],
["hook (fire extinguishing)", "갈고리" ],
["electric light bulb", "잔등" ],
["work costume", "작업복" ],
["cloth hanger", "옷걸이" ],
["ear plug", "귀마개" ],
["fabric glove", "면장갑" ],
["screw bolt", "볼트" ],
["forceps/tongs/pincer", "집게" ],
["grass", "목초" ],
["spanner/adjustable wrench", "스패너" ],
["plastic", "비닐" ],

["tray", "쟁반" ],
["mailbox", "우폔함" ],
["first aid kit", "구급함" ],
["toolbox", "공구함"],
["gas pump", "주유기" ],
["crane", "기중기" ],
["shelf", "선반" ],
["rubber", "고무" ],
["engine", "엔진" ],
["cart (behind the vehicle)", "끌개" ],
["leek", "부추" ],
["wagon", "수레" ],
["lifting machine/lift", "승강기" ],
["cutter", "절단기" ],
["welding machine", "용접기" ],
["water filter", "급수기" ],

["bench/working spot", "작업대" ],
["ancient stone tablet/monument", "조상기" ],
["outlet", "콘센트" ],
["wire","전선"],
["iron plate", "철판" ],
["ice", "얼음" ],
["electricity control board/panel board", "분전반" ], 
["hygiene garment/cloth", "위생복" ],
["wrapping paper", "포장지" ],
["kettle", "주전자" ],
["sprinkling can", "물뿌리개" ],
["household car", "승합차" ],
["ambulance","구급차"],
["excavator", "굴삭기" ],
["ladder car", "사다리차" ],
["rubber glove", "고무장갑" ],
["slip", "전표" ],
["paint", "페인트" ],
["dormitory", "기숙사" ],
["workplaceplace/work room", "작업실" ],
["nursery/fish tank", "양식장" ],
["pigsty", "돈사" ],
["car garage", "창고" ],
["living room", "휴게실" ],
["construction site", "공사장" ],
["pick/pickax", "곡괭이" ],
["claw hammer", "장도리" ],
["broom", "빗자루" ],
["plane(ing) tool", "대패" ],
["hacksaw", "쇠톱" ],
["rake", "쇠스랑" ],
["container", "컨테이너" ],
["electric weight scaling machine", "전자저울" ],
["electric drill", "전기드릴" ],
["animal food mixing machine", "배합사료" ],
["blinder/shade cover", "차광막" ],
["breaker", "개폐기" ],
["watersprout/drainage", "배수구" ],
["welding stick", "용접봉" ],
["stove", "난로" ],
["washing machine", "세척기" ],
["hydraulic machine", "유압기" ],
["bulldozer", "불도저" ],
["rice planting vehicle", "이앙기" ],
["cold room car", "냉동차" ],
["cargo ship", "화물선" ],
["conveyor", "컨베이어" ],
["excavator", "포클레인" ],
["floor(level of building)/story", "층" ],
["worth (တန်)", "짜리" ],
["building", "건물" ],
["wan", "원" ],
["fishing boat", "고기잡이배" ],
["chicken", "닭" ],
["black tea", "홍차" ],
["coin", "동전" ],
["greenhouse", "비닐하우스" ],
["week", "주" ],
["month", "달" ],
["year", "년" ],
["chicken egg", "계란" ],
["cold noodle dish", "냉면" ],
["oil", "기름" ],
["dining room", "식당" ],
["playground", "운동장" ],
["running", "달리기" ],
["window", "창문" ],
["stairs", "계단" ],
["go up the stairs", "올라가다" ],
["elevator", "엘리베이터" ],
["mountain", "산" ],
["gymnastics", "체조" ],
["pick up", "줍디" ],
["fire burn", "불이 나다" ],
["flood occur", "물난리가 나다" ],
["traffic accident happen", "교통사고가 나다" ],
["traffic light/blinker", "신호등" ],
["stand in line", "줄을서다" ],
["gather", "모이다" ],
["conersation", "이야기" ],
["sea", "바다" ],
["boat", "배" ],
["way", "길" ],
["picture", "그림" ],
["paint (v)", "그리다" ],
["riverside", "강변" ],
["floorcloth/dustcloth", "걸레" ],
["table", "탁자" ],
["towel", "수건" ],
["face", "얼굴" ],
["grandma", "할머니" ],
["dine", "식사를 하다" ],
["camera man", "사진사" ],
["beautician", "미용사" ],
["go to bed", "주무시다" ],
["examine (health check)", "진찰하다" ],
["broad", "넓다" ],
["not enough", "부족하다" ],
["enough", "넉넉하다" ],
["noisy", "떠들다" ],
["quiet", "조용하다" ],
["in the room", "실내" ],
["dark", "컴컴하다" ],
["bright", "밝다" ],
["cry", "울다" ],
["laugh", "웃다" ],
["tired", "피곤하다" ],
["mind", "기분" ],
["mind happy", "기분이좋다" ],
["angry", "화가나다" ],
["voice", "소리" ],
["scream the voice loudly", "소리를지르다" ],
["scream","지르다"],
["music", "음악" ],
["game", "게임" ],
["dryer", "드라이어" ],
["get it dried", "말리다" ],
["hang/call", "걸다" ],
["comb", "빗" ],
["cup", "컵" ],
["water put inside the cup", "컵에든물" ],
["in/lift", "들다" ],
["hand", "손" ],
["pot", "냄비" ],
["sleep", "잠을자다" ],
["mouth", "입" ],
["necktie", "넥타이" ],
["choose", "고르다" ],
["suit", "양복" ],
["western coat", "양복윗옷" ],
["dining table", "식탁" ],
["ball/zero", "공" ],
["play football", "축구를하다" ],
["outside the window", "창밖" ],
["dangerous", "위험하다" ],
["floor", "바닥" ],
["slippery", "미끄럽다" ],
["office", "사무실" ],
["clean (state)", "깨끗하다" ],
["nice (personality)", "친절하다" ],
["living room", "거실" ],
["toilet", "화장실" ],
["few", "적다" ],
["kitchen", "부엌" ],
["accumulate", "밀리다" ],
["traffic", "교통" ],
["complicated", "복잡하다" ],
["marathon", "마라톤" ],
["hungry", "고프다" ],
["view", "경치" ],
["look around", "구경하다" ],
["neck", "목" ],
["turn (head)", "돌리다" ],
["raise (leg)", "올리다" ],
["bend (waist)", "구부리다" ],
["arm", "팔" ],
["height", "높" ],
["high", "높다" ],
["lift arm", "팔을높이드다" ],
["same", "같다" ],
["stand", "서다" ],
["lie down", "눕다" ],
["lie face down/prostrate oneself", "엎드리다" ],
["snow(v)", "눈이오다" ],
["snow/eye", "눈" ],
["cold (snow)", "춥다" ],
["cold (rain)", "쌀쌀하다" ],
["cold (wind)", "시원하다" ],
["windy", "바람이불다" ],
["wind", "바람" ],
["cloudy", "구름이많다" ],
["cloud", "구름" ],
["day is dim", "날이흐리다" ],
["fix/repair", "고치다" ],
["day", "날" ],
["dim", "흐리다" ],
["engage in farming", "농사를짓다" ],
["agriculture", "농사" ],
["do fishing", "낚시를하다" ],
["fishhook", "낚시" ],
["coat", "외투" ],
["put on shoes", "신발을싣다" ],
["shoe", "신발" ],
["tie", "묶다" ],
["unravel/untie", "풀다" ],
["wash hair", "샴푸를하다" ],
["nurse", "간호사" ],
["inject the syringe", "주사를놓다" ],
["feed", "먹이다" ],
["hug", "안다" ],
["a letter", "글씨" ],
["talk on phone", "통화를하다" ],
["clear the snow", "눈을치우다" ],
["tidy up", "치우다" ],
["throw away", "버리다" ],
["ajumma", "아주머니" ],
["laundry", "빨래" ],
["dishwashing", "설거지" ],
["very", "많이" ],
["catch/last (cold)", "걸리다" ],
["thing", "것" ],
["where", "어디" ],
["ကျွန်တော်က","제가" ],
["ငါက", "내가" ],
["နင်က", "네가(니가)" ],
["ဘယ်သူက", "누가" ],
["spring", "봄" ],
["summer", "여름" ],
["autumn", "가을" ],
["winter", "겨울" ],
["season", "계절" ],
["season", "철" ],
["train station", "기차역" ],
["yes,that's right ", "네 맞습니다" ],
["no, that's wrong ", "아니요 틀립니다" ],
["nothing", "아무것" ],
["only", "만" ],
["workplace", "직장" ],
["colleague", "동료" ],
["together", "함께" ],
["bad", "나쁘다" ],
["so", "그래서" ],
["if not put on (glasses)", "쓰지않으면" ],
["well", "잘" ],
["forest fire occur", "산불이나다" ],
["number", "번호" ],
["number", "번" ],
["museum", "박물관" ],
["firefighter station", " 소방서" ],
["eat/lift/put", "들다(드세요)" ],
["prescription", "처방전" ],
["toothpaste", "치약" ],
["headache pill", "두통약" ],
["antibiotic medicine", "항생제" ],
["peptic", "소화제" ],
["busan journey", "부산행" ],
["sold out", "매진다" ],
["call", "전화하다" ],
["seat", "좌석" ],
["express terminal" ,"고속버스터미널"],
["morning", "아침" ],
["get up", "일어나다" ],
["အဲဒီအရာကတော့", "그건/그것은" ],
["အဲလိုဆိုရင်", "그럼" ],
["ရှိလားဆိုတာ", "있는지" ],
["မေးကြည့်သည်", "물어보다" ],
["traditional", "전통" ],
["when", "언제" ],
["new year", "설날 (설랄)" ],
["or", "나/이나" ],
["thanksgiving", "추석" ],
["လိုမျိုး", "같은" ],
["holiday", "명절" ],
["marriage", "결혼식" ],
["vegetable", "야채/나물" ],
["fish", "생선" ],
["laundry shop", "세탁소" ],
["side dish", "반찬" ],
["dessert", "후식" ],
["more", "더" ],
["foot", "발" ],
["box office", "매표소" ],
["information bureau", "안내소" ],
["management office", "관리사무소" ],
["service center", "서비스센터" ],
["farm", "농장" ],


["give/close the shop", "주다/드리다" ],
["repair center", "수리센터" ],
["bathing", "목욕" ],
["drive", "운전" ],
["take care", "주심하다" ],
["traffic light", "신호" ],
["accident", "사고" ],
["parking", "주차" ],
["nationality", "오국" ],
["id card/certificate", "등록증" ],
["register", "등록" ],
["ambassy", "대사관" ],
["police station", "경찰서" ],
["town/ward office", "동사무소" ],
["immigration management office", "줄입국관리사무소" ],
["present", "선물" ],
["letter(paper of)", "편지" ],
["always", "항상" ],
["prize", "포상" ],
["come in", "들어오다" ],
["passenger", "승객" ],
["ladies and gentlemen", "여러분" ],
["safety line", "안전선" ],
["want/wish/hope", "바라다" ],
["vacate/back off", "물러나다" ],
["host/landlord", "주인" ],
["guest", "손님" ],
["chinese", "중국" ],
["about how much", "얼마나" ],
["remittance", "송금" ],
["bank book", "통장" ],
["be apologic", "미안하다" ],
["have time/free", "시간이있다" ],
["appointment/promise", "약속" ],
["calculation", "계산" ],
["stream train", "기채열차" ],
["depart", "출발하다" ],
["minute", "분" ],
["gimchi soup", "김치찌개" ],
["coffee shop", "커피숍" ],
["road/avenue", "도로" ],
["public place", "공공장소" ],
["သန့်သန့်ရှင်းရှင်း", "깨끗이" ],
["apologize", "죄송하다" ],
["air-con", "에어컨" ],
["debit/credit card", "신용카드" ],
["exchange (v)", "교환하다" ],
["refund/money-back", "환불" ],
["supermarket", "슈퍼마켓" ],
["classroom", "교실" ],
["လပိုင်း", "월" ],
["ရက်နေ့", "일" ],
/*
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
*/

  ]
 /* 
const Grammer = [
  ["၏/ရဲ့","의"],
  ['ဖြစ်ပါတယ်','N+입니다'],
  ['ဖြစ်ပါသလား','N+입니까'],
  ['ကတော့/သော','N+은/는'],
  ['က','N+이/가'],
  ['ပါတယ်','V+.ㅂ니다/습니다'],
  ['ပါသလား','V+.ㅂ니까/습니까'],
  ['ကို','N+을/를'],
  ['ကို','N+에(가다,오다)'],
  ['မှာ','N+에서'],
  ['မှာ','N+에(있다,계시다,없다,살다,많다,앉다)'],
  ['and','N+와/과'],
  ['and','N+하고'],
  ['and','N+랑/이랑'],
  ['and','N+및'],
  ['ကြမလား/ရမလား','V+을까요/.ㄹ까요'],
  ['မဘူး','V+지못합니다'],
  ['မဘူး','V+지않습니다'],
  ['ချင်တယ်','V+고싶습니다'],
  ['ပါ','V+세요/으세요'],
  ['ပါ','V+십시오/으십시오'],
  ['နေပါတယ်/ထားပါတယ်','V+고있습니다'],
  ['မလို့ပါ','V+려고합니다/으려고합니다'],
  ['ရင်/လျှင်','V+면/으면'],
  ['ချင်ရင်','V+려면/으려면'],
  ['ရင်းနဲ့','V+면서/으면서'],
  ['သောအခါ/တဲ့အခါ','V+을때/.ㄹ때'],
  ['လည်းပဲ','N+도'],
  ['ပြီးတော့','V+고'],
  ['အစ','N+부터'],
  ['အထိ','N+까지'],
  ['မဘူး','안+V'],
  ['ပြီးတော့/သောကြောင့်','V+(아,어,해)서'],
  ['ဖြင့်/နဲ့/သို့','V+로/으로'],
  ['သော','V+는'],
  ['ခဲ့သော','V+은/ㄴ'],
  ['လုပ်ကြည့်သည်',' V+(아,어,해)보다/보여요'],
  ['လုပ်ပေးသည်း','V+(아,어,해)주다'],
  ['မယ့်','V+(을/ㄹ)'],
  ['ခဲ့တယ်','V+(았,었,했)어요/습니다'],
  ['လိမ့်မယ်','V+을/ㄹ 거예요'],
  ['မလို့ပါ','V+려/으려 고해요'],
  ['တဲ့အတွက်ကြောင့်', 'V+기때문에'],
  ['ဘာဖြစ်ပါသလဲ','뭐여요'],
  ['ပါတယ် / ပေမယ့်', 'V+는데'],
  ['လုပ်ရမယ်','V+(아,어,해)야해요'],
  ['လုပ်နိုင်တယ်','V+을/ㄹ 수있다'],
  ['လုပ်မနိုင်ပါ','V+을/ㄹ 수없다'],
  ['ယဥ်ကျေး','V+시다/으시다'],
  ['ဆိုတာ','V+는지'],
  ['ပြီးတော့/သောကြောင့်','V+니까/으니까'],
  ['မဟုတ်လား','N+지요/이지요'],
  ['ဖြစ်ဖြစ်/သို့မဟုတ်','N+나/이나'],
  
  ]
  */
   
  
export const words = rawIntoReady(raw)
