
const derived = "derived"
const eng = "eng"
const grammarAndExtra = "grammar&extra"
const sentence = "sentence"

export const two = [
  
["right ", "오른쪽" ],
["left", "왼쪽" ],
["ဖြစ်ပါတယ်", "돼요", sentence ],
["colour", "색깔" ],
["used/second-handed", "중고" ],
["စျေးပေါစွာ", "싸게", grammarAndExtra  ],
["rehab center", "재활용센터" , derived ], 
["rehabilitation/rehab", "재활" ],
["dragon/use", "용" ],
["realestate dealer", "부동산중개소" ],
["unshakeable", "부동" ],
["every month/monthly", "매달" , derived ],
["every month/monthly", "매월" , derived ],
["every week", "매주" , derived ],
["every year", "매년" , derived ],
["every dag", "매일" , derived ],
["all", "모두" ],
["all", "다" ],
["အဲဒီနေ့ကို", "그날을", sentence],
["fine/penalty", "벌금" ],
["monthly salary", "월급"  , derived ],
["tax", "세금" ],


["security deposit/guarantee money", "보증금" ],
["different/other", "다른" , derived ],
["monthly payment (rent)", "월세" , derived ],
["lump sum of deposit (for years/no repaid)", "전세" ],
["transportation ecpense/ကားခ", "차비" , derived ],
["theater", "극장" ],
["theater", "연극" ],
["is free of charge", "무료이다" ],
["free", "무료" ],
["free", "공짜" ],
["သွားပြီးပြန်လာခဲ့ပါတယ်", "갔다왔어요" , sentence ],
["inquire", "알아보다" ],
["inquire", "문의하다" ],
["rest", "쉬다" ],
["easy", "쉽다" ],
["difficult", "어렵다" ],
["finding employment/getting a job", "취업" ],
["education", "교육" ],
["အလုပ်ဝင်ပညာပေးဌာန ", "취업교육기관", derived ],
["employment/hiring", "고용" ],
["အလုပ်ခန့်စင်တာ", "고용안정센터", derived ],
["documents/paperwork", "서류" ],
["copying", "복사" ],

["how much", "몇" ],
["instant noodle", "라면" ],
["ကြာဇံ", "국수" ],
["city hall/municipal office building", "시청" , derived ],
["front", "앞" ],
["behind", "뒤" ],
["under", "아래" ],
["under", "밑" ],
["next to/beside", "옆" ],
["transportation card (to pay)", "교통카드" , derived ],
["end of the month (days)", "월말" , derived ],
["end of the year", "연말" ],
["end of semester/finals", "기말" ],
["saving/savings", "저금" ],
["stand/build/establish/set", "세우다" ],
["park car", "차를세우다" , sentence ],
["lay out plan", "계획을세우다" , sentence ],
["plan", "계획" ],
["order (restaurant)", "주문" ],
["go shopping (market)", "장을보다" , sentence ],
["မှာကြားသည်", "지키다" ],
["မှာကြားသည်", "주문하다", derived ],
["ဘယ်လိုလုပ်မလဲ ", "어떡하죠" , sentence ],
["lost", "잃다" ],
["lost", "잃어버리다" ],
["lost", "분실하다" ],
["lost things center", "분실물센터" , derived ],
["lonh", "길다" ],
["usually/normally", "보통" , sentence ],
["blocked/clogged", "막이다" ],
["overpass/footbridge", "육교" ],
["underground tunnel", "지하도" , derived ],
["crosswalk/zebra crossing", "횡단보도" ],
["how", "어떤" , sentence ],
["occupation/profession", "직업" ],
["about/around", "쯤" ],
["about/around", "정도" ],
["employee", "직원" ],
["addrees", "주소" ],
["reading", "독서" ],
["character/personality", "성격" ],
["work/job", "업무" ],
["bussiness/work", "사업" ],
["place of bussiness", "사업장" , derived ],
["welfare", "복지" ],
["give welfare", "복지하다" , derived ],
["welfare center", "복지센터" , derived ],

["fax", "팩스" , eng ],
["consult/counsel ", "상담" ],
["consulting center", "상담센터" , derived ],
["korean language teaching class", "한국어교육기관" , derived ],
["eye clinic", "안과" , derived ],
["internal clinic", "내과" , derived ],
["dental clinic", "치과" , derived ],
["external clinic", "외과" , derived ],
["calcutate/estimate cost", "계산하다" , derived ],
["dollar", "달러" ],
["evening", "저녁" ],
["alcolohilic beverage", "술" ],
["company dinner", "회식" ],
["going to work", "출근" ],
["leaving work", "퇴근" ],
["ခဏလေးပါ", "잠깐만요"  , sentence ]   ,
["alittle", "조금" ],
["red", "빨간" , derived ],
["ဖြစ်ပါတယ်", "이에요", grammarAndExtra ],
["aspect/facet/direction/way", "방면" ],
["have/bring", "가지다" ],

["ယူသွားသည်", "가져가다" , derived ],
["ဆင်းသွားသည်", "내려가다" , derived ],
["ခေါ်ဆောင်သည်", "데리다" ],
["ခေါ်ဆောင်သွားသည်", "데려가다", derived ],
["go up/climb", "올라가다" ],
["train station", "역" ],
["မြေထွန်သည်", "밭을갈다" , sentence ],
["2လိုင်း", "2호선" , derived ],
["transfer/change transportation", "갈아타다" , derived ],
["transfer/change transportation", "환승하다" ],
["come back/return", "돌아오다" , derived ],
["department manager/team-leader", "과장님" ],
["seat/place", "자리" ],
["မရှိပါ", "안계신데요" , sentence ],
["memo", "메모" , eng ],
["ချန်ထားပေးရမလား", "남겨드릴까요" , sentence ],
["leave behind", "남기다" ],
["later", "나중에" ],
["one more", "다시" ],
["cook rice", "밥을짓다" , sentence],
["cook rice", "밥을하다" , sentence ],
["do farming", "논을짓다" , sentence],


["arriving", "도착" ],
["already", "벌써" ],
["daughtet", "딸" ],
["son", "아들" ],
["get a job", "취직하다" ],
["seek/look for/ကယ်ဆယ်", "구하다" ],
["hello", "여보세요"  , sentence ],
["house", "집" ],
["ဖြစ်သည်", "이다" , sentence ],
["cut/trim (price)", "깎다" ],
["finish", "끝내다" ],
["first/in advance", "먼저" ],
["အရင်ပြန်နှင့်ပါ", "먼저 들어가세요", sentence ],
["gas fee", "가스비" , derived],
["ထွက်လာသည် (cost)", "나오다" ],
["almost/neay", "거의" , sentence ],
["food waste", "음식물" ],
["environment", "환경" ],

["pollution", "오염" ],
["serious/grave", "심각하다" ],
["serious", "심하다" ],
["bored", "심심하다" ],
["lazy/indolent", "게으르다" ],
["platform (train station. airport)", "승강장" ],
["between/relationship/gap", "사이" ],
["fall off/come off/left out/remove", "빠지다" ],
["worry", "염려" ],


//last
["country number", "국가번호" , derived ],
["region number", "지역번호" , derived ],
["type (v)", "누르다" ],
["tear apart", "찢다" ],
["farry", "통근" ],
["erase", "지우다" ],
["depart", "떠너다" ],
["miss (bus)", "놓치다" ],
["push/shave", "밀다" ],
["pull", "당기다" ],//10
["long holiday", "연휴" ],
["သွားပြီးပြန်လာသည်", "다녀오다" ],
["impact/shock", "충격" ],
["pride", "자랑" ],
["get angry", "화내다" ],
["employer", "고용주" , derived ],
["person that manage", "관리자" , derived ],
["management", "관리" ],
["holiday", "휴일" ],
["appointment location", "약속장소", derived ],//20
["ကနေ", "에서" ],
["get off from underground train", "지하철에서내리다" , sentence],
["cloth hanger (wooden, in korea traditional house)", "묵걸이" ],
["tie pin", "넥타이핀" , eng ],
["opposite side/facing side", "건너편"],
["opposite side/facing side", "맞은편"],
["newspaper company", "신문사" , derived],
["sit/take a seat", "좌하다" , derived ],
["rinse", "행구다" ],

//60 day chanllange start
//12.5.2023
["following", "다음" ],
["cover (book/ads)/ mm", "표지" ],
["signboard/noticeboard", "표지판" , derived ],
["under construction", "공사중" ],
["explaination", "설명" ],
["safety helmet", "안전모" , derived ],
["wear/put on(not daily cloth)", "착용하다" ],
["make right turn", "우회전하다" ],
["make left turn", "좌회전하다" ],
["ban/prohibition", "금지" ],
["beside/in addition to", "이외" ],
["ဆောက်လုပ်ရေးနှင့်သက်ဆိုင်သူမှအပ", "공사관게자이외" , sentence ],
["meaning", "뜻" ],
["speed", "속도" ],
["fall/drop (vertical)", "떨어지다" ],
["decrease", "줄다" ],
["reduce", "줄이다" ],
["rock/stone", "돌" ],
["ကျောက်ခဲပြိုကျနယ်မြေ", "낙석붕괴지역", derived ],
["ဖြေးဖြေး", "천천이" ],
["zone/region", "구역" ],
["zone/region", "지역" ],
["exclisive/dedicated", "전용" ],
["pass by/go past", "지나가다" ],
["one-direction/တဖက်လားရာ ", "한쪽방향" ],
["one-way street", "일방통행" ],
["body", "신체" ],
["chest", "가슴" ],
["navel", "배꼽" , derived ],
["buttock", "엉덩이" ],
["forearm", "팔뚝" , derived ],
["groin", "사타구니" ],
["thigh", "허벅지" ],
["knee", "무릎" ],
["shin/ညိုသကျည်း ", "정강이" ],
["nape", "목덜미" , derived ],
["elbow", "팔꿈치" , derived ],
["back", "등" ],
["calf", "종아리" ],
["hair", "머리카락", derived ],
["forehead", "이마" ],
["temple/နားထင် ", "관자놀이" ],
["eyebrow", "눈썹" , derived],
["eyelash", "속눈썹" , derived ],
["nostril", "콧구멍", derived ],
["cheek", "뺨" ],
["lip", "입술" , derived ],
["chin", "턱" ],
["jaw", "아래턱" , derived ],
["mole/မှဲ့ ", "사마귀" ],
["man", "남성" , derived ],
["woman", "여성" , derived ],


//2 
["overwork", "과적" , derived ],
["luggage/baggage", "짐" ],
["tool/equipment", "공구" ],
["in place/သူ့နေရာနဲ့သူ", "제자리" ],
["problem", "문제" ],
["put/place (with attention)", "두다" ],
["every/each (individual focus)", "마다" ],
["once per time/တစ်ကြိမ်စီ", "한번씩" ],
["1st /တစ်ကြိမ်မြောက်", "첫번째" ],
["guard/keep/လိုက်နာသည်", "지키다" ],
["matter/issue", "사항" ],
["warning/caution", "경고" ],
["smoke-free zone", "금연구역" ],
["smoke/light a cigar", "피우다" ],
["maintenance/repair", "정비" ],
["order of use", "사용순서" , derived ],
["order", "순서" ],
["electricity power supply", "전원" , derived ],
["operate/စက်နှိုးသည်", "작동" ],
["speak", "말하다" ],
["person in charge", "현장소장" ],
["finger", "손가락" , derived ],
["toe", "발가락" , derived ],
["sole/ခြေဖဝါး", "발바닥", derived ],
["instep/ခြေဖမိုး", "발등안쪽", derived ],
["heel", "발뒤꿈치", derived ],
["big-toe", "엄지발가락" , derived],
["wrinkle", "주름살" ],
["freckle/တင်းတိပ်", "주근깨" ],
["pore/ချွေးပေါက်", "모공" ],
["dimple", "보조개" ],
["thumb", "엄지" ],
["index finger", "검지" ],
["middle finger", "중지" ],
["ring finger", "약지" ],
["little finger", "새끼손가락" ],
["wrist", "손목" , derived ],
["palm", "손바닥" , derived ],
["nail", "손톱" , derived ],
["knuckle", "손가락관절" ],
["fist", "주먹" ],
["uncle", "삼촌" ],
["aunty", "숙모" ],
["husband", "남편" ],
["wife", "아내" ],
["brothers", "형제" ],
["sisters", "자매" ],
["cousin", "사촌" ],
["daughter-in-law", "며느리" ],
["son-in-law", "사위" ],


//3 
["grandson", "손자" ],
["granddaughter", "손녀" ],
["relatives", "친척" ],
["generation", "세대" ],
["parents", "부모님" ],
["offsprings", "자녀" ],
["grandchildren", "손주" ],
["grand parents", "조부모" ],
["step mother", "계모" ],
["step father", "계부" ],
["လင်ပါ/မယားပါသား", "으붓아들" ],
["လင်ပါ/မယားပါသမီး", "의붓딸, derived" ],
["partner", "동거인" ],
["twins", "쌍동이" ],
["monther-in-law", "배우자의어머니" ],
["father-in-law", "배우자의아버지", derived ],
["brother-in-law", "배우자의남자형제" , derived],
["sister-in-law", "배우자의여자형제" , derived],
["niece", "여조카" ],
["nephew", "남조카", derived ],
["stages", "단게" ],
["child", "어린이" , derived ],
["little boy", "남자아이" , derived ],
["teenagers", "청소년" ],
["adult", "성인" ],
["relationships", "대인관계" ],
["assistant", "비서" ],
["right answer", "정답" , derived ],
["bussiness paretner", "임원" ],
["neighbour", "이웃" ],
["acquaintance", "지인" ],
["girlfriend", "여자친구" , derived ],
["couple", "커플" , eng ],
["fiance man", "약흔자" ],
["fiance woman", "약흔녀" , derived ],
["engaged couple", "약흔한커플", derived ],
["emotions", "감정" ],
["happy/delight", "행복하다" ],
["smile ( N )", "미소" ],
["excited", "흥분하다" ],
["suprised", "놀라다" ],
["frightened", "경악하다" ],
["frightened", "악연하다" ],
/*
["frown", "찌푸리다" ],
["vague (feel)", "막연하다" ],
["ashamed/shy", "부끄럽다/창피하다" ],
["shocked", "충격을받다" ],
["faint", "기절하다" ],
["life's significant line", "인생중대사" ],
["start school", "취학하다" ],
["graduate", "졸업하다" ],
["divorce", "이혼" ],
["birth certificate", "출생증명서" ],
["retire", "은퇴하다" ],
["will", "유언장" ],
["christmas", "성탄절" ],
["bat", "박쥐" ],
["surname", "성" ],
["language school", "어학당" ],
["instructor", "강사" ],
["economic department", "경제학과" ],
["law/legal study", "법학" ],
["medical study", "의학" ],
["politics", "정치학" ],
["English study", "영문학" ],
["management study", "경영학" ],
["fill", "채우다" ],
["pink", "분홍색" ],
["gray", "회색" ],
["brown", "갈색" ],
["purple", "보라색" ],
["green", "초록색/녹색" ],



*/


["sigh", "한숨짓다" ],
["yawn", "하품하다" ],
["worry", "걱점하다" ],
["lovely", "사랑스럽다" , derived ],
["proud", "자랑스럽다" , derived ],
["be self-confident", "자신만만하다" ],

["born", "태어나다" ],
["make friend", "친구를사귀다" , sentence ],
["fall in love", "사랑에빠지다" , sentence ],
["emigrate", "이민가다" ],
["have a baby", "아이를낳다" , sentence ],

/*


*/
["banquet", "피로연" ],
["honeymoon", "신혼여행" ],
["ribbon", "리본" , eng ],
["festival", "축제" ],
["candy", "사탕" ],
["pumpkin", "호박" ],
["wizard", "마법사" ],
["witch", "마녀" ],
["ghost", "귀신" ],
["တကယ့်ကို", "정말" ],
["တကယ့်ကို", "참" ],
["university", "대학교" , derived ],
["greeting", "인사" ],
["introduction", "소개" ],

["ဘယ်", "어느" ],
["japan", "일본" ],
["ဟုတ်ပါသလား", "그렇습니까"  , sentence ],
["nationality/citizenship", "국적" ],
["bank employee", "은행원" , derived ],
["delighted", "반갑다" ],
["lawyer", "변호사" ],
["reporter", "기자" ],
["connect/link", "연결하다" ],
["saleman/salewoman", "점원" ],
["magazine", "잡지" ],

//5
["pen case", "필통" ],
["blackboard", "칠판" ],
["small", "작다" ],
["basketball (sport)", "농구" ],
["question", "질문" ],
["beer", "맥주" ],
["location", "위치" ],
["cat", "고양이" ],
["church", "교회" ],
["juice", "주스" , eng ],
["seaweed rice", "김밥" ],
["every day", "날마다" ],
["homework", "숙제" ],
["sometime", "가끔" ],
["interesting", "재미있다" ],
["classmate", "반친구" ],
["cover (v)", "덮다" ],
["follow/imitate", "따라하다" ],
["learning/ လေ့ကျင့်ခန်း", "학습" ],
["learning/ လေ့ကျင့်ခန်း", "연습" ],
["goal/objective/ခေါင်းစဥ်   ", "목표" ],
["information", "정보" ],
["culture", "문화" ],
["etiquette/manners/ကျင့်ဝတ်  ", "예절" ],
["greeting manners", "인사예절" , derived ],
["dialogue/conversation", "대화" ],
["Nepal", "네팔" , eng ],
["Vietnam", "베트남" , eng ],
["Thailand", "태국" , eng ],
["Philippine", "필리필" , eng ],
["example", "보기" ],
["လိုမျိုး ", "처럼" ],
["sentence", "문장" ],
["complete/finish", "완성하다" ],
["pronunciation", "발음" ],
["housewife", "주부" ],
["civil servant", "공무원" ],
["technician/skilked worker", "기술자" ],
["carpenter/woodworker", "목수" ],
["farmer", "농부" , derived ],
["fisherman", "어부" ],
["နှင့်ပတ်သက်သည် ", "에대하다" ],
["activity/  ", "활동" ],
["မိမိထက် ", "자신보다", derived ],
["position/status/ ", "지위" ],
["first", "처음" ],
["သိသောလူ", "아는사람" , sentence],
["ရင်းနှီးသောလူ", "친한사람", sentence ],


//6
["young/immature", "어리다" ],
["close/freindly", "친하다" ],
["word/မီးနင်း ", "단어" ],
["noisy/loud", "시끄럽다" ],
["opposite word/antonym", "반대말" ],
["East Timor", "동티모르" , eng],
["Mongolia", "몽골" , eng],
["Myanmar", "미얀마" , eng],
["Bangladesh", "방글라데시" , eng],
["Sri Lanka", "스리랑카" , eng],
["Uzbekistan", "우즈베키스탄" , eng],
["Cambodia", "캄보디아" , eng],
["Kyrgyzstan", "키르기스스탄" , eng ],
["Pakistan", "파키스탄" , eng ],
["grammar", "문법" ],
["place", "장소" ],
["ဘဝရပ်တည်နေထိုင်ခြင်း", "생활" ],
["necessity/essential item", "필수품" , derived ],
["living necessity", "생활필수품" , derived ],
["toiletries/bathroom essentials", "세면도구" , derived ],
["mart", "마트" , eng ],
["ဒါနဲ့", "그런데", sentence ],
["ဒီအရာက", "이게" , derived],
["အဲဒီအရာက", "저게" , derived ],
["ဟိုအရာက", "그게" , derived ],
["cosmetics/makeup", "화장품" , derived ],
["put on makeup", "화장하다" , derived ],
["hair dryer", "헤어드라이어" , eng],
["most/majority", "대부분" ],
["rinse/ဆံပင်ပျော့ဆေး", "린스" , eng ],
["toothbrush", "칫솔", derived ],
["razor/shaving tool", "면도기" ],
["AM", "오전" ],
["PM", "오후" ],
["daytime", "낮" ],
["low/short", "낮다" ],
["night", "밤" ],
["snake", "뱀" ],
["dawn", "새벽" ],
["preparation", "준비" ],
["preparation for work", "일할준비" , sentence ],
["9နာရီဆိုရင်", "9시라면" , sentence],
["night shift ", "야근" ],
["situation/case", "경우" ],
["situation/case", "상태" ],
["situation/case", "상황" ],
["ကြီး", "대" ],
["အပိုင်းအခြား", "부분" ],
["warm", "따뜻하다" ],
["major", "전공" ],
["computer subject/computer science", "컴퓨터공학" , derived],


//7
["working hours/တနေ့တာ", "일과" ],
["wife (formal)", "부인" ],
["smart", "똑똑하다" ],
["stylish/cool", "멋있다" ],
["slim/slender", "날씬하다" ],
["chubby/plump", "뚱뚱하다" ],
["well behaved/quiet", "얌전하다" ],
["diligent", "부지런하다" ],
["not really/သိပ်ပြီးတော့", "별로" ],
["သိပ်မရင်းနှီးသောလူ", "별로가깝지않은사람", sentence ],
["close/near", "가깝다" ],
["on the other hand/တစ်ဖက်မှာကတော့", "한편"  , derived ],
["public holiday", "공휴일" , derived ],
["movement", "동작" ],
["ဘယ်နေ့ရက်", "며칠" ],
["အင်တာနက်ဆိုင်", "pc방", eng ],
["way/approarch", "방식" ],
["way/approarch", "방법" ],
["verb", "동사" ],
["go shopping", "쇼핑하다" , eng ],
["အနောက်တိုင်းနှစ်သစ်ကူး", "신정(양력설날)" ],
["3.1တော်လှန်ရေးနေ့", "삼일절", derived ],
["အလုပ်သမားနေ့", "근로자의날", derived ],
["ကလေးများနေ့", "어린이날"  , derived ],
["ဗုဒဖွားသောနေ့", "석가탄신일" ],
["အာဇာနည်နေ့", "현충일" ],
["လွတ်လပ်ရေးနေ့", "광복절" ],
["ပြည်ထောင်စုနေ့", "개천절" ],
["ကိုးရီးယားစာထွင်သောနေ့", "한글날" , derived ],
["christmas", "크리스마스" , eng ],
["but/ဒါပေမယ့်", "하지만" , sentence ],
["like this/ဒီလိုမျိုး", "이런", sentence ],
["alone", "혼자" ],
["outgoing/energetic/lively", "활발하다" ],
["congratulate", "축하하다" ],
["thank", "감사하다" ],
["Noun", "명사" ],
["position/sitting posture", "좌식" ],
["beauty salon/hair salon", "미용실" , derived ],
["အတိုကောက်စကား", "줄임말" ],
["appearance", "외모" ],
["အမြင့်သုံးစကား", "높임말", derived ],
["အနိမ့်သုံးစကား", "반말" ],
["big sister", "언니" ],
["show/indicate", "표시하다" ],
["announce/present", "발표하다" ],
["borrow", "빌리다" ],

["Japan restaurant", "일식집" , derived ],
["Chinese restaurant", "중국집" , derived],
["Western restaurant", "양식집" , derived ],
["grilled meat", "불고기" , derived ],
["reason", "이유" ],
["related/relevant", "관련" ],
["အဲလိုလုပ်ကြတာပေါ့", "그럽시다" , sentence ],
["main gate", "정문" ],
["Japan food", "일식" , derived ],
["ပဲခေါက်ဆွဲ", "짜장면" ],
["sushi", "초밥" ],
["ice-cream", "아이스크림" , eng],
["vinegar/ရှာလကာရည်", "식초" ],
["soy sauce/ငံပြာရည်", "간장" ],
["ငရုတ်ဆီ", "고추장" ],
["play", "놀다" ],
["steak", "스테이크" , eng ],
["chocolate", "초콜릿", eng ],
["နံရိုး/rib", "갈비" ],
["ဝက်သားသုံးထပ်သား", "삼겹살" ],
["နံရိုးစွပ်ပြုတ်", "갈비탕" ],
["ပဲပိစပ်", "된장" ],
["တိုဟူး", "순두부" ],
["chicken rib", "닭갈비" ],
["ဂျင်ဆင်းကြက်ပေါင်း", "삼계탕" ],
["ခေါက်ဆွဲကြီး (လက်လုပ်)", "칼국수" ],
["တော့ပိုကီ", "떡볶이" ],
["ကြာဇံကြော်", "잡채" ],
["menu", "차림표" ],
["menu", "메뉴" ],
["ဆလပ်ရွက်", "상추" ],
["recommand", "권하다" ],
["eat (အမြင့်သုံး)", "잡수시다" ],
["number", "숫자" ],
["unit", "단위" ],
["red tea", "홍차", derived ],
["green tea", "녹차" , derived ],
["ထမင်းကြော်", "볶음밥" ],
["ဝက်ချိုချဥ်", "탕수육" ],
["employee", "종업원" ],
["find", "찾다" ],
["organize/tidy up", "정리하다" ],
["comfirm/verify", "학인하다" ],
["appropriate/suitable", "적당하다" ],
["porridge/ယာဂု", "죽" ],
["seaweed soup", "미역국" ],
["second (time)", "초" ],
["part-time job", "아르바이트" , eng],
["daily", "하루" ],
["studio apartment", "원룸" , eng ],
["avoid/evade (physical)", "비키다" ],


//9
["boarding house/rented room ", "하숙집" ],
["exam/test", "시험" ],
["vacasion/holiday", "방학" ],
["graduation ceremony", "졸업식" ],
["at that time", "그때" , derived],
["overseas travel", "해외여행" , derived ],
["beautiful (scene)", "아름답다" ],
["beoadcast", "방송" ],
["rainy season", "장마" ],
["stationery store", "문방구" ],
["rose", "장미꽃" , derived ],

["black", "끼만색" ],
["black", "검은색" ],
["white", "흰색" ],
["white", "하얀색" ],
["orange", "주황색" ],
["strong/sturdy", "튼튼하다" ],
["weak/feeble", "약하다" ],
["thick", "두껍다" ],
["cheese", "치즈" , eng ],
["animal", "동물" ],
["cola", "콜라" , eng ],
["flower bouquet", "꽃다발" ],
["gift card/boucher", "상품권" ],
["doll", "인형" ],
["accessories", "액세서리" , eng ],
["sunglasses", "선글라스", eng ],
["various/diverse", "여러가지" ],
["dance (v)", "춤을추다" , sentence ],
["dance (n)", "춤" ],
["pull/drag", "추다" ],
["wine", "와인" , eng ],
["measure/weight", "메다" ],
["excuse me/pardon me", "실례" ],
["exit", "출구" ],
["this direction", "이쪽" , derived ],
["deliver/send", "부치다" ],
["hotel", "호텔" , eng ],
["art museum/gallery", "미술관" ],
["straightness/uprightness/ ", "똑바호" ],
["alumni", "동문" ],
["north gate", "북문" , derived ],
["west gate", "서문" , derived ],
["early", "일찍" ],
["south gate", "남대문" , derived ],

//10 
["normal/common", "일반" ],
["standard taxi", "일반택시" , derived ],
["premium/deluxe taxi", "모범택시" ],
["urban bus", "시내버스", derived ],
["orange", "오렌지" , eng ],
["groceries/foodstuffs", "식료품" , derived ],
["currency", "화폐" ],
["purchasing goods", "물품구매" , derived ],
["pack/wrap", "싸다" ],
["pack/wrap", "포장하다" ],
["middle/center", "가운데" ],
["middle/center", "중간" ],
["be leisurely/unoccupied", "한가하다" ],
["simple", "간단하다" ],
["comfortable", "편하다" ],
["uncomfortable", "불편하다" , derived ],
["is possible/feasible", "가능하다" ],
["impossible", "불가능하다" , derived ],
["delivery", "배달" ],
["stop/cease (rain/snow/argument) ", "그치다" ],
["clear/bright (sky)", "맑다" ],
["enjoyable", "즐겁다" ],
["exciting/thrilling(party) ", "신나다" ],
["refreshing", "상쾌하다" ],
["sleepy/drowsy (adv)", "졸리다" ],
["lonely/solitary", "외롭다" ],
["feel depressed/down", "우울하다" ],
["cabbage", "배추" ],
["contact/communication", "연락" ],
["email", "이메일" , eng ],
["keep a promise", "약속을지키다", sentence ],
["to run behind schedule", "차가밀리다" ],
["touch", "만지다" ],
["lawn/grass field", "잔디밭" ],
["art exhibition (event/can be outside)", "그림전시회" , derived ],
["announcement", "안내방송" , derived ],
["condo", "콘도" , eng ],
["raw fish dish", "회" ],
["intersection/crossroads of 4", "길거리" ],
["intersection/crossroads of 4", "사거리" ],
["straight ahead (direction)", "직진" ],
["straight ahead (direction)", "똑바로" ],
["serve/carry", "모시다" ],
["in a moment", "잠시후" , sentence ],
["later (close)/ခဏကြာပြီးနောက်", "이따가", sentence ],
["right away/immediately", "바로" ],
["dial incorrectly/make wrong call", "잘못걸다" , derived ],
["ring/sound", "울리다" ],
["phone is ringing", "전화벨이울리다" , sentence ],
["text message", "문자메시지" , derived ],
["voice message", "음성메시지" , derived ],
["to get along/compatible ", "어울리다" ],
["change/alter (apperance/characteristic of something)", "비꾸다" ],
["sound of car horn", "때르릉" ],


//11
["clothing/garments", "의류" ],
["field of medicine/healthcare", "의료" ],
["target (attention/discussion)/ဦးတည်ချက် ", "대상" ],
["ဦးတည်ချက်ကိုလိုက်ပြီးတော့", "대상에따라서" , sentence ],
["count", "세다" ],
["request", "요청하다" ],
["request help", "부탁하다" ],
["command/order", "명령" ],
["express/manifest", "나타내다" ],
["formal or bussiness suit", "정장" ],
["jacket/jeogori", "잠바" ],
["slipper", "슬리퍼" , eng ],
["muffler", "목도리" , derived ],
["movement", "이동" ],
["rooftop/terrace", "옥상" ],
["signpost/guidepost", "이정표" ],
["alley/small lane", "골목" ],
["decide/fix (problem)/define", "정하다" ],
["comedy", "코미디" , eng ],
["genre", "장르" , eng ],
["melodrama/romance", "멜로" , eng ],
["action", "액션" , eng ],
["horror", "공포" ],
["hope/desire (improvement)", "희망" ],
["governmant office/public sector", "관공서" ],
["provincial government office", "도청" , derived ],
["main center/headquarter", "주만센터" ],
["resident center/community center", "주민센터" ],
["propose idea", "제안하다" ],
["break up/part way", "헤어지다" ],
["next time/later", "다음에" , sentence],
["လို့ဆိုသော", "라는"  , sentence ],
["လို့", "라고", grammarAndExtra ],
["especially/particularly", "특히" , derived ],
["be exceptional/extraordinary", "특히다" ],
["feel disappointed/regret", "아쉽다" ],
["detail", "구체" ],
["specificially/in detail", "구체적으로" , derived ],
["thinking", "생각" ],
["if/in case", "만약에" , sentence ],
["rest/break", "휴식" ],
["avoid/evade (someone/danger)", "피하다" ],
["also/in addition", "또한" , sentence ],
["in advance/beforehand", "미리" ],
["together/attached/ထပ်ပြီးတော့", "붙어서", sentence ],
["formality/etiquette", "격식" ],
["plate/dish", "접시" ],
["ကျနော်ကတော့", "전" , sentence],
["spicy pork bone stew", "감자탕" ],
["spicy seafood noodle soup", "짬뽕" ],
["fried dumplings/potstickers", "군만두" ],
["squeeze in/insert oneself in (crowd)", "끼어앉다" ],

//12
["breaded and deep-fried pork cutlets", "돈가스" , derived ],
["thick wheat noodle", "우동" ],
["buckwheat noodle", "모밀" ],
["deep-fried foods", "튀김" ],
["stuffed pig intestines dish", "순대" ],
["fried chicken", "치킨" , eng ],
["braised pig's trotter dish", "족발" ],
["boiled pork belly dish", "보쌈" ],
["pizza", "피자" , eng ],
["အစာပြေ", "분식" ],
["သရေစာ", "간식" ],
["ညလယ်စာ", "야식" ],
["continuously", "계속" ],
["adverb", "부사" ],
["real/တကယ်?", "진짜" ],
["ပန်းကြွေအအေးဒဏ်", "꽃새추위" ],
["ဖုန်လေ", "황사" ],
["ပန်းကြည့်ခြင်း", "꽃구경" ],
["အလွန်ပူခြင်း", "무더위" ],
["rainy season", "장마철" ],
["အပူရှောင်ခြင်း", "피서" ],
["အရောင်ပြောင်းပန်းကြည့်ခြင်း", "단풍놀이" ],
["ချဥ်ဖတ်စိမ်ခြင်း", "김장" ],
["သုံးရက်အေးလေးရက်ပူ", "삼한사온" ],
["အအေးစစ်သူကြီး", "동장군" ],
["snowman", "눈사람" , derived ],
["ice fishing", "얼음낚시" , derived ],
/*
["to hang/put up curtain", "커튼을치다" ],
["to cover/tuck in the blanket", "이불을덮다" ],
["doze off/nod off", "졸다" ],
["set an alarm", "알람을맞추다" ],
["spread out/unfold the blanket", "이불을펴다" ],
//["", "잠을섷치다" ],
["brush teeth", "이를갈다" ],
["to dream", "꿈을꾸다" ],
["sleep talk", "잠꼬대를하다" ],
["pick one's nose", "코를골다" ],
["to toss and turn", "뒤척이다" ],
["open one's eyes (after sleep)", "눈이떠지다" ],
["sunlight", "햇빛" ],
["to be glaring/dazzling", "눈이부시다" ],
["to rub one's eyes", "눈을비비다" ],
["stretch oneself", "기지개를켜다" ],
["alarm rings", "알람이울리다" ],
["turn on the lights", "불을켜다" ],
["tidy up the bed", "침대를정리하다" ],
["to open/draw back the curtain", "커튼을걷다" ],
["wake someone up", "깨우다" ],
["spread out/unfold the blanket", "이불을개다" ],
["to sleep in/take late nap", "늦잠을자다" ],

["curtain ","커튼"],
["alarm","알람"],
["to match/guess/adjust","맞추다"],
["dream","꿈"],
["sleep talking","잠꼬대"],
["pick","골다"],
["float/detach/vanish","떠지다"],
["rub/wipe","비비다"],
["stretch","기지개"],
//13
["take shower", "샤워하다" ],
["water pressure is strong", "수압이세다" ],
["the water pressure is weak", "수압이약하다" ],
["to apply soap/to lather with soap", "비누칠을하다" ],
["squeeze the shower gel/body wash", "바디워시를짜다" ],
[" squeeze out body cleanser", "바디클렌저를짜다" ],
["body wash is running out", "바디워시가떨어지다" ],
["massage the back", "등을밀다" ],
["dry the body with a towel", "수건으로몸을닦다" ],
["apply body lotion", "바디로션을바르다" ],
["foam appears", "거품이나다" ],
["rinse your hair with water", "머리를물로적시다" ],
["bow one's head and wash hair", "머리를숙이고감다" ],
["dilute shampoo", "샴푸를덜다" ],
["massage the scalp", "두피를마사지하다" ],
["scratch or rub the scalp", "두피를문지르다" ],
["hair/head fall off", "머리가빠지다" ],
["wash ones face", "세수하다" ],
["cotton pad(makeup)", "화장솜" ],
["remove makeup", "화장을지우다" ],
["dispense facial cleanser onto the palm", "세안제를손바닥에덜다" ],
["turn on water/open water faucet", "물을틀다" ],
["close ones eyes", "눈을감다" ],
["splash water on the face", "얼굴에물을묻하다" ],
["lather/rub/apply soap", "비누를문지르다" ],
["wash with water", "물로행구다" ],
["brush ones teeth", "양치하다" ],
["open ones mouth", "입을벌리다" ],
["drop toothbrush", "칫솔을떨어드리다" ],
["someone else's toothbrush", "남에칫솔" ],
["electric toothbrush", "전동칫솔" ],
//["", "가글하다" ],
["squeeze toothpaste", "치약을짜다" ],
["disinfect toothbrush", "칫솔을소독하다" ],
["wash mouth", "입을행구다" ],
["electric shaver", "전기면도기" ],
["beard is short", "수염이짧다" ],
["shave", "면도하다" ],
["shaving cream", "쉐이빙크림" ],
["touch/stroke chin", "턱을만지다" ],
["neat/tidy/clean", "깔끔하다" ],
["het wound/injured", "상처가나다" ],
["cut with razor blade", "면도날에베이다" ],
["shave the beard", "수염을밀다" ],
["lenses/contact kenses", "렌즈" ],
["glasses feel heavy(thick glasses)", "안경이헐겁다" ],
["remove lenses", "렌즈를빼다" ],
["undergo eye examination/vision test", "시력검사를받다" ],
["to have the right diopter (lenses)", "도수가맞다" ],


["weakened", "약히다" ],
["apply/polish/draw", "칠하다" ],
["salty/squeeze/do/concentrate", "짜다" ],
["body lotion", "바디로션" ],
["foam", "거품" ],
["memorize/save/arrive on time/deliver", "적시다" ],
["bow/lower(v)/reflect thought/yield(lose)", "숙이다" ],
["dilute/substract/put certain amount", "덜다" ],
["scalp", "두피" ],
["massage", "마사지" ],
["rub/stroke", "문지르다" ],
["facial cleanser", "세안제" ],
["brushing teeth", "양치" ],
["open/spread/be profitable", "벌리다" ],
["disinfect/sterilize", "소독하다" ],
["beard", "수염" ],
["touch/stroke", "만지다" ],
["cut/nick", "베이다" ],
["razor blade", "면도날"],
["heavy/be burdened", "헐겁다" ],
["remove/take out", "빼다" ],
["vision test", "시력검사" ],
["diopter(lense)", "도수" ],


//14
["eyeglass frames", "안경테" ],
["eyeglass store", "안경점" ],
["glasses are foggy", "안경이쪼이다" ],
["to have glasses adjusted", "안경을맞추다" ],
["there is a hole in the cloth", "옷에구멍이나다" ],
["to button up", "단추를잠그다" ],
["try on clothes", "옷을입어보다" ],
["zip up", "지퍼를올리다" ],
["change clothes", "옷을갈아입다" ],
["ruin/mess up makeup", "화장을망치다" ],
["mascara", "마스카라" ],
["spray mist (perfume)", "미스트를뿌리다" ],
["show ones bare face", "민낯을보여주다" ],
["paint over/apply a coat of paint", "덧칠하다" ],
["curl eyelash", "속눈썹을올리다" ],
["deceive/trick", "속이다" ],
["draw eyebrows", "눈썹을그리다" ],
["make up is being removed", "화장이지워지다" ],
["fix/adjust makeup", "화장을고치다/수정하다" ],
["slice/tell story/analyze (problem)", "썰다" ],
["ingredients", "재료" ],
["sharpen/change/reconcile", "갈다" ],
["boil", "끓이다" ],
["knead dough", "반죽하다" ],
["apply oil/grease", "기름을두르다" ],
["burn a pot", "냄비를태우다" ],
["grill/roast", "굽다" ],
["oven", "오븐" ],
["measure time", "시간을재다" ],
["taste(v)/sample flavour", "간을보다" ],
["stir-fry", "볶다" ],
["spill rice", "밥을흘리다" ],
["arrange side dish", "반찬투정을하다" ],
["pick up with chopstick", "젓가락으로집다" ],
["scoop with spoon", "숟가락으로뜨다" ],
["devour/eat voraciously", "배어먹다" ],
["swallow", "삼키다" ],
["cook/prepare rice", "밥을푸다" ],
["detergent", "세제" ],
["tablewares/dishes", "식기" ],
["plates collide with each other", "그릇이서로부딪치다" ],
["scrub sponge", "수세미" ],
["soak dishes in water", "그릇을물에담그다" ],
["have stain/residue on dish", "그릇에금이가다" ],
["drop a dish", "그릇을떨어뜨리다" ],
["classify/categorize dishes", "그릇을분류하다" ],
["break a dish", "그릇을깨뜨리다" ],
["take out an item", "물건을꺼내다" ],
["lift furniture", "가구를들다" ],
["operate vacuum cleaner", "청소기를돌리다" ],


["foggy/misted", "쪼이다" ],
["hole", "구멍" ],
["button", "단추" ],
["lock/close", "잠그다" ],
["zip", "지퍼" ],
["lift/raise", "올리다" ],
["ruin/mess up/spoil", "망치다" ],
["mist", "미스트" ],
["sprinkle/scatter", "뿌리다" ],
["bare face", "민낯" ],
["modify/edit", "수정하다" ],
["apply/put on", "두르다" ],
["burn/ignite", "태우다" ],
["liver/taste/interval/meeting", "간" ],
["bake/roast", "푸다" ],
["bump/collide into", "부딪치다" ],
["spill/let something flow", "흘리다" ],
["sulking/throwing tantrum", "투정" ],
["soak/immerse", "담그다" ],
["drop", "떨어뜨리다" ],
["break/shatter", "깨뜨리다" ],
["take out/retrieve", "꺼내다" ],
["classify/categorize", "분류하다" ],


//15
["brush off the dust", "먼지를털다" ],
["sweep the floor", "바닥을쓸다" ],
["plug in", "플러그를꽂다" ],
["to unplug", "플러그를뽑다" ],
["ventilate/air out", "환기시키다" ],
["replace vacuum cleaner filter", "청소기필터를갈다" ],
["run washing machine", "세탁기를돌리다" ],
["take out the laundry from the washing machine", "빨래를세탁기에서빼다" ],
["sort the laundry", "빨랫감을분류하다" ],
//["", "건소하다" ],
["remove a stain", "얼룩을지우다" ],
["leave clothes at a dry cleaner", "세탁소에옷을맡기다" ],
//["", "빨래를개다" ],
["hang laundry", "빨래를널다" ],
["fertilizer", "거름" ],
["grow/mature", "자라다" ],
["flower pot/potted plant", "화분" ],
["sprout/seedling", "새싹" ],
["raise/nurture", "기르다" ],
["prune(cut branches)", "가지치기하다" ],
//["", "열메가열리다" ],
["pick flowers", "꽃을꺾다" ],
["flowers bloom", "꽃이피다" ],
["harvest fruits", "열매를따다" ],
["mobile phone", "핸드폰" ],
["phone is ringing", "전화밸이울리다" ],
["voice", "목소리" ],
["to be heard/audible", "들리다" ],
//["", "저정하다" ],
["rebroadcast/rerun", "재방송" ],
["tv schedule/guide", "TV편성표" ],
["screen appears/display", "화면이나오다" ],
["make tv appearance", "TV에출연하다" ],
["change channel", "체널을돌리다" ],
["install cable tv", "케이블TV를설치하다" ],
["personal story/narrative", "사연" ],
["increase volume/turn up sound", "소리를키우다" ],
["signal not received well", "신호가잘안잡히다" ],
["play music", "음악을틀다" ],
["song request", "신청곡" ],
["be selected as winner", "당첨하다" ],
["lower volume", "소리를줄이다" ],
["have radio playing all day", "라디오를 하루종일 틀어놓다" ],
["web surfing", "웹서핑" ],
["open web browser", "브라우저를열다" ],
["register as member/sign up", "회원가입을하다" ],
["log out", "로그아읏" ],
["log in", "로그인" ],
["news", "뉴스" ],
["subscribe to newsletter", "뉴스레터를신청하다" ],



["pluck hair/search thoroughly/cheat/strip forcefully", "털다" ],
["sweep/write/erase", "쓸다" ],
["dust/dirt", "먼지" ],
["plug", "플러그" ],
["vacuum cleaner filter", "청소기필터" ],
["clothes being washed", "빨랫감" ],
["stain", "얼룩" ],
["entrust/leave in someone's care", "맡기다" ],
["open/rip/unfold/express/cause", "개다" ],
["hang/spread something out", "널다" ],
["open", "열리다" ],
//["", "열메" ],
["bend/fold", "꺾다" ],
["fruit", "열매" ],
//["", "전화밸" ],
["ring/make a sound", "울리다" ],
["screen/display", "화면" ],
["appear/perform", "출연하다" ],
["channel", "체널" ],
["turn/rotate", "돌리다" ],
["cable tv", "케이블TV" ],
["install/setup", "설치하다" ],
["raise/nurture", "키우다" ],
["play/start (video,machine)", "틀다" ],
["web browser", "브라우저" ],
["sign up", "회원가입" ],
["apply/request", "신청하다" ],
["newsletter", "뉴스레터" ],
*/

//16 
["concert", "콘서트" , eng ],
["sports game", "운동경기" ],
["gittar", "기타" , eng ],
["piano", "피아노" , eng ],
["tennis", "테니스" , eng],
["bowling", "볼링" , eng],
["batminton", "배드민턴" , eng ],
["golf", "골프" , eng],
["skate", "스케이트", eng ],
["ski", "스키" , eng],
["play tennis", "테니스를치다" , sentence],
["play bowling", "볼링을치다" , sentence],
["play batminton", "배드민턴을치다" , sentence ],
["play golf", "골프를치다" , sentence],
["ride skate", "스케이트를타다" , sentence],
["ride ski", "스키를타다" , sentence ],
["cave", "동굴" ],
["waterfall", "폭포" ],
["lake", "호수" ],
["river", "강" ],
["island", "섬" ],
["hot spring", "온천" ],
["historic/archaeological site", "유적지" ],
["folk/traditional village", "민속촌" ],
["amusement park", "놀이공원" , derived ],
["drama filming location", "드라마촬영지", derived ],
["be famous", "유명하다" ],
["plan the trip", "여행을계획하다" , sentence ],
["make a lodging reservation", "숙소를예약하다" , sentence],
["pack luggage", "짐을싸다" , sentence],
["unpack luggage", "짐을풀다" , sentence ],
["stay (short term)", "묵다" ],
["visit museum", "박물관을관람하다" , sentence ],
["enjoy/witness a festival", "축제를구경하다" , sentence ],
["buy souvenirs", "기념품을사다" , sentence],
["local/village bus", "마을버스" ],
["intercity bus", "시외버스" , derived ],
["taxi stand/rank (location)", "택시승강장" , derived ],
["pier/wharf", "여객터미널" ],
["pier/wharf", "선착장" ],
["go on foot", "걸어가다" , derived ],
["pass/go by", "지나다" ],
["programme", "프로그램" , eng ],
["frequency", "빈도" ],
["adjective", "형용사" ],
["club/assiosiation", "동호회" ],
["gathering/meeting", "모임" , derived ],
["purpose/objective", "목적" ],
["various regions", "각지역" ],
["manpower", "인력" ],
["welfare/support", "지원" ],
["multicultural", "다문화" , derived ],
["အစရှိသဖြင့်", "등에서" , sentence],
["for", "을위해" , sentence ],
["various", "다양한" ],
["Taekwondo", "태권도" , eng ],

["lodging/accomodation", "숙소" ],
["filming", "촬영" ],
["visit/observe (paid)", "관람하다" ],
["festival", "축제" ],
["souvenirs", "기념품" , derived],
["village", "마을" ],


//17
["through/မှတဆင့်လုပ်", "을통하여" , sentence ] ,
["enjoy", "즐기다" ],
["class", "수업" ],
["review/leisure time", "휴기" , derived ],
["experience", "경험" ],
["Tourist destination", "관광지" , derived ],
["ဘယ်လိုလဲ", "어땠어요"  , sentence ],
["motel", "여관" ],
["ဒေသခံအိမ်", "민박" ],
["pension/ဘန်ဂလို", "펜션", eng ],
["youth hostel", "유스호스텔" , eng ],
["east", "동" ],
["west", "서" ],
["south", "남" ],
["north", "북" ],
["use", "이용" ],
["cruise ship", "유람선" ],
["beach", "해수욕장" ],
["be aware", "알아두세요" ],
["organization", "단체" ],
["clinic/consulting office", "상담소" ],
["cheap", "싸다/저렴하다" ],
["method", "수단" ],
["disturbance", "소요" ],
["public transport", "대중교통" , derived ],
["during", "중에" ],
["choose", "선택하다" ],
["office attend/leave time", "출퇴근" , derived ],
["transportation cost", "교통비" , derived ],
["payment", "결제" ],
["buying", "구입" ],
["buying", "구매" ],
["charge (v,money)", "충전" ],
["store", "매점" , derived ],
["money charging machine/charger", "충전기" ],
["amount", "금액" ],
["participate", "참여하다" ],
["write a blog", "블로그에글을쓰다" , sentence ],
["upload a picture", "사진을올리다" , sentence ],
["before", "이전" , sentence ],
["new", "새로" ],
["fix", "고침하다" ],
["go to favourites ", "즐겨찾기에등콕하다" , sentence ],  ///hhhhhhhhhhhhhhhhhhhh
["put down/left a scroll (flower)", "스크롤을내리다" , sentence ],
["book is boring", "책이지루하다" , sentence ],
["do underline", "밑줄을긋다" , sentence ],
["read inside (with mind)", "속으로읽다" , sentence ],
["read aloud", "소리내어읽다" , sentence ],
["cross ones leg", "다리를꼬다" , sentence ],
["shake ones leg", "다리를떨다" , sentence ],
["squat (sit)", "쭈르리고앉다" , sentence ],


["blog", "블로그" , eng],
["writing", "글" ],
["favourites", "즐겨찾기" ],
["go back", "등콕하다" ],
["scroll", "스크롤" , eng ],
["underscore/underline", "밑줄" , derived ],
["genus/inside", "속" ],
["twist", "꼬다" ],
["shiver", "떨다" ],
["shrink", "쭈르리다" ],
["drop", "떨어드리다" ],


  ]