

const derived = "derived"
const eng = "eng"
const grammarAndExtra = "grammar&extra"
const sentence = "sentence"


export const three = [

["handphone", "휴대푼" , derived ],
["smartphone", "스마트폰" , eng ],
["internet", "인터넷" , eng ],
["make a phone call", "전화를걸다" , sentence ],
["phone call incoming", "전화가오다" , sentence ],
["change/transfer the call", "전화를바꾸다" , sentence ],
["accept the call", "전화를받다" , sentence],
["make wrong call", "전화를잘못걸다" , sentence ],
["wrong", "잘못" ],
["disconnect/terminate", "끊다" ],
["cut off the call", "전화를끊다" , sentence ],
["be in the middle of phone call", "통화중이다" , sentence ],
["open the phone", "휴대전화를켜다" , sentence ],
["close the phone", "휴대전화를끄다" , sentence ],
["text message", "문자" ],
["send massage", "문자를보내다" , sentence],
["check massage", "문자를확인하다" , sentence ],
["confirm/စစ်ဆေး", "확인하다" ],
["website", "웹사이트" , eng ],
["search", "검색" ],
["search engine", "검색엔진" , derived ],
["homeoage", "홈페이지" , eng ],
["internet cafe", "인터넷카페" , eng],
["member", "회원" ],
["sign up", "가입" ],
["withdraw/unsubscribe", "탈퇴" ],
["membership registeration", "회원가입" , derived ],
["membership withdrawal", "회원탈퇴" , derived ],
["id", "아이디" , eng ],
["secret", "비밀" ],
["passward", "비밀번호" , derived ],
["internet search", "인터넷검색", derived ],
["chatting", "채팅" , eng ],
["video call", "화상" ],
["video call chatting", "화상채팅" , derived],
["to be confused/disoriented/messy", "어지럽다" ],
["to be organized/tidy", "정돈되어있다" ],
["brush off the dust", "먼지를떨다" , sentence ],
["cleaning tools", "청소도구" , derived ],
["tissue box", "휴지통" , derived ],
["house chores", "집안일" , derived ],
["rice cooker", "밥솥" , derived ],
["fry pan", "프라이팬" , eng ],
["kitchen liquid detergent", "주방세제" , derived ],
["collect the hanged cloth", "빨래를걷다" , sentence ],
["iron the cloth", "옷을다리다" , sentence ],
["fold the cloth", "옷을개다" , sentence ],

["be useful", "유용하다" ],
["convenient", "편리하다" ],
["registration number", "등록번호" , derived],
["crime", "범죄" ],
["report", "신고" ],
["phone number directory", "전화번호안내" , derived ],
["fire (accident)", "화재" ],
["emergency", "구급" ],
["emergency", "응급" ],
["emergency", "긴급" ],
["patient", "환자" ],
["occurance", "발생" ],
["basic/foundation", "기초" ],
["region/local area", "지방" ],
["local autonomous orrganization", "지방자치단체" , derived ],
["various/all kinds of/အသီးသီး ", "각종" ],
["citizen complaint/public grievance", "민원" , derived ],
["weather forecast", "일기예보" , derived ],
["forecast/prediction", "예보" ],
["stay/residence", "체류" ],
["အစရှိသဖြင့်", "등" , sentence ],
["ministry of employment and labor", "고용노동부" , derived ],
["customer/client", "고객" ],
["immigrant woman", "이주여성" ],
["emergency support center", "긴급지원센터" , derived ],
["resident/citizen", "주민" ],
["interpretation", "통역" ],
["translation", "번역" ],
["သောအရာ", "는것"  , sentence ] ,  
["separation/division", "분리" ],
["collection/pick-up", "수거" ],
["disposal", "배출" ],
["willpower/volition", "의지" ],
["ရှေ့ရှောက်", "앞으로"  , sentence],
["separate waste disposal", "분리수거" , derived ],
["pay-as-you-throw/unit based pricing system", "종량제" ],
["actual/real", "실제" ],
["emission/discharge volume", "배출량" , derived ],
["ကို လိုက်ပြီးတော့", "에따라" , sentence ],
["commission/fee", "수수료" ],
["imposition/levying", "부과" ],
["effect/impact", "효과" ],
["system/institution", "제도" ],
["designated/prescribed", "지정된" , derived ],
["designated/prescribed", "정해진" , derived ],
["to designate/assign", "지정하다" , derived ],
["standard/specification", "규격" ],
["sell/to market", "판매하다" , derived ],
["put/store", "담다" ],
["လွှင့်ပစ်အောင်လို့", "버리도록" , sentence ],
["recycling", "재활용" ],
["exclude/omit", "제외하다" ],
["raise/heighten", "높이다" , derived ],
["ချန်လှစ်ပြီးတော့", "제외하여" , sentence ],
["nationwide", "전국" ],
["nationwide", "전국적으로" , derived],
["implement/carry out", "실시하다" ],
["dampness/moisture", "물기" , derived ],
["type/kind", "종류" ],
["according to the standard", "규격별로" , derived ],
["bulky waste", "대형쓰레기" , derived ],
["paper waste", "종이류" ],
["empty bottles", "빈병" ],
["plastic", "플라스틱" , eng ],
["demolish/dismantle/ဟောင်းသည် ", "헐다" ],
["used clothing for donation/အဝတ်ဟောင်း", "헌옷" , derived],
["fluorescent light bulb/မီးချောင်း", "형광등" ],
["battery", "건전지" ],
["collection bin", "수거함", derived ],
["နီးစပ်ရာ", "가까운" , derived ], 

["be messy/untidy", "지저분하다" ],
["express/convey", "표현" ],
["make an appointment", "약속을하다" , sentence ],
["break a promise/appointment", "약속을어기다" , sentence ],
["violate/break", "어기다" ],
["do visitation", "방문을하다" , sentence ],
["visit(n)", "방문" ],
["invitation", "초대" ],
["prepare/organize/tidy up", "장만" ],
["table/goods/condition/prize", "상" ],
["set up the table/prepare a feast", "상을차리다" , sentence ],
["set up/prepare/provide/equip(room)", "차리다" ],
["clear the table", "상을치우다" , sentence ],
["chat", "이야기를나누다" , sentence ],
["go out to greet someone", "마중나가다" , derived ],
["လိုက်ပို့သည်", "배옹하다" ],
["smoke free", "금연" ],
["no food and drink allowed", "음식물반입금지" , derived ],
["bring something inside", "반입" ],
["cellphone useage prohibited", "휴대전화사용금지" , derived ],
["no photography", "사진촬영금지" , derived ],
["indoor silence", "실내정숙" , derived ],
["silence", "정숙" ],
["no entry", "출입금지" , derived ],
["near/approach/access", "접근" ],
["no access", "접근금지" , derived ],
["unauthorized", "무단" ],
["crossing/crosswalk", "횡단" ],
["no jaywalking", "무단횡단금지" , derived ],
["no parking", "주차금지" , derived ],
["no speeding", "과속금지" , derived ],
["overeating", "과식" , derived ],
["smoke cigarettes ", "담배를피우다" , sentence ],
["cigarette butt/stub", "담배꽁초" ],
["saliva/spit", "침" ],
["spit", "침을뱉다" , sentence ],
["run around", "뛰어다니다" , derived ],
["noisy", "고성방가하다" ],
["act of cutting in line", "새치기" ],
["cut in line", "새치기를하다" , sentence ],
["occupy/take up", "차지" ],
["occupy the place", "자리를차지하다" , sentence],
["sit with legs spread", "다리를벌려서앉다" , sentence ],
["spread/expose", "벌리다" ],
["touch/handle", "손대다" , derived ],
["vocabulary", "어휘" ],
["speak", "말씀하시다" , derived ],
["speech/horse", "말" ],
["unwell", "편찮으시다" ],
["unwell", "앓다" ],
["unwell", "아프다" ],
["die", "돌아가시다" ],
["လက်တစ်ဖက်ဖြင့်", "한손으로", sentence ],
["insert a spoon into the rice", "밥에숟가락을꽂다" , sentence],
["insert/plant/pierce", "꽂다" ],
["eat while holding the rice bowl", "밥그릇을들고먹다" , sentence],
["make a loud sound (eating)", "소리를크게내다" , sentence ],
["sound of eating", "쩝" ],
["neck/head", "고개" ],
["turn ones head (drinking)", "고개를돌리다" , sentence],
["bend ones waist (greeting)", "허리를숙이다" , sentence ],
["yield/give way", "양보하다" ],
["give up ones seat", "자리를양보하다" , sentence ],
["shoe cabinet", "신발장" , derived],
["လုပ်ပေမယ့်", "하는데"  , grammarAndExtra],
["လှပေမယ့်", "예쁜데"  , grammarAndExtra],
["ယောက်ျားဖြစ်ပေမယ့်", "남자인데" , grammarAndExtra ],
["maunfacturing industry", "제조업" , derived],
["construction industry", "건설업" , derived ],
["livestock industry", "축산업" , derived ],

["bring later", "이따오다" ],
["preparing meal", "상차리" , derived ],
["permission/approval", "허락" ],
["permission/approval", "허가" ],
["soon", "곧" ],
["very soon", "금방" ],
["ဘာကို", "뭘"  , sentence],
["အရာကို", "걸"  , sentence ],
["be popular", "인기가있다" , sentence],
["popularity", "인기" ],
["become", "되라다" ],
["meaning", "으미" ],
["as a gift", "선물로" , sentence ],
["answer", "답다" ],
["be very easy", "술술풀리라다" ],
["new house", "새집" , derived ],
["the rich", "부자" ],
["happen", "생기다" ],
["decorative items", "장식용품" , derived ],
["newly married coupled", "신혼부부" , derived ],
["married couple", "부부" ],
["cutlery set", "수저세트" , derived ],
["give present", "선물하다" ],
["captain", "반장님" ],
["last weekend", "지난주말" , derived ],
["even if its small", "작은것이라도" , sentence ],
["sharing with each other", "서로나누는것" , sentence ],
["several", "여러" ],
["egg plant", "가지" ],
["several", "여러가지" , derived ],


//22
["lately/မကြာသေးခင်က", "얼마전" , sentence ],
["လုပ်ရာက", "하다가" , sentence ],
["get hurt", "다치다" ],
["concert hall", "공연장" , derived ],
["handicapped seating", "노약자석" , derived ],
["the elderly", "노약자" ],
["old man", "노인" ],
["disabled (person)", "장애인" ],
["pregnant woman", "임산부" ],
["နေရာဖြစ်တဲ့အတွက်ကြောင့်", "자리이기때문에", sentence ],
["vacate", "비우다" ],
["even if you sit down", "앉더라도" , sentence ],
["answer", "대답" ],
["charge(v)", "충전하다" ],
["suddenly", "갑자기" ],

//23
["adult", "어른" ],
["advise", "조언하다" ],
["အသက်ဆိုသော", "나이란" , sentence ],
["because/ဖြစ်သောကြောင့်", "거라서", sentence ],
["drink(n)", "음료수" ],
["3 years ago", "3년전" , sentence ],
["underlined part", "밑줄친부분" , derived ],
["suffering", "고생" ],
["yet", "아직" , sentence ],
["eat quietly", "조용히먹다" , derived ],
["panic", "당황" ],
["no", "아닙니다" ],
["because", "왜냐하면" , sentence ],
["besides", "말고도", sentence ],
["finish/end", "마치다" ],
["gitar/etc", "기타" ],
["detail", "내용" ],
["relate", "관계이다" , derived],
["we/my", "저희" ],

//24
["application", "신청" ],
["employee/worker", "근로자" ],
["find in dictionary", "사전을찾다", sentence ],
["go to school/class", "학원에다니다" , sentence],
["preview", "예습" ],
["review", "복습" ],
["lecture", "강의" ],
["car maintenance", "차정비" , derived ],
["return", "돌아가다" , derived ],
["help(n)", "도움" ],
["similar", "비슷하다" ],
["understanding", "이해" ],
["procedure", "과정" ],
["subject", "과목" ],
["schedule", "일정" ],
["agency", "기관" ],
["certificate", "자격증" ],
["start(class)", "개강" ],
["end(class)", "종강" ],
["industry", "산업" ],
["corporation", "공단" ],
["fuction", "기능" ],
["ability", "능력" ],
["required function", "필요기능" , derived ],
["period", "기간" , derived ],
["getting (acquire)", "습득" ],
["home country", "본국" ],
["stability", "안정" ],
["safety", "안전" ],
["resettlement", "재정착" ],
["offer", "제공" ],
["local", "현지" ],
["current", "현재" ],
["status", "현황" ],
["company", "기업" ],
["demend survey", "수요조사" ],
["re-employment", "재취업" , derived ],


["or/တစ်နည်းအားဖြင့်", "혹은"  , sentence],
["founded", "창업" ],
["composition", "구성" ],
["agriculture and livestock industry", "농축산업" , derived ],
["fishing", "어업" ],
["site", "현장" ],
["practical(adj)", "실용적이다" ],
["management", "관리" ],
["job (responsibility)", "직무" , derived ],
["as well as/ သာလျှင်မကပဲ", "뿐만아니라"  , sentence],
["specialty", "전문" ],
["technology", "기술" ],
["improve", "향상시키다" ],
["include", "포함" ],
["such", "이러한" , sentence ],
["effort", "열심" ],
["make friends with", "사귀다" ],
["test", "시험" ],
["there is a test", "시험이있다" , sentence ],
["history", "역사" ],
["writing/စာပုဒ်", "글" ],
["question", "물음" ],
["middle class", "중급" ],
["beginner class", "초급" ],
["advanced class", "고급" ],
["direct visit", "직접방문" , derived],
["notice/", "안내문" , derived ],
["tuition fee", "수업료" , derived ],
["deduction", "공제" ],
["directly", "직접" ],

//25
["buddhism", "불교" ],
["christian", "기독교" ],
["buddhist temple", "절" ],
["monk", "스님" ],
["church", "교회" ],
["pastor", "목사님" ],
["catholic", "천주교" ],
["catholic", "가톨릭" , eng ],
["cathedral", "성당" ],
["father", "신부님" ],
["islam", "이슬람교" ],
["mosque", "사원" ],
["mosque", "모스크" , eng ],
["imam", "이맘" , eng ],
["beliver", "신자" ],
["beliver", "교인" , derived ],
["pay a tribute/ ဗုဒရှိခိုး", "예불을드리다"  , sentence],
["worship/ခရစ်ယာန် အစ်စလာမ် ရှိခိုး ", "예배를드리다" , sentence],
["say mass/ မယ်တော်မာရီယာရှိခိုး", "미사를드리다",sentence ],
["sing a hymn", "찬불가를부르다" , sentence],
["sing a chant", "성가를부르다", sentence ],
["prepayment/ ဗုဒရှိခိုး", "예불" ],
["worship/ ခရစ်ယာန် အစ်စလာမ် ရှိခိုး", "예배" ],
["mass/မယ်တော်မာရီယာ", "미사" ],
["hymns", "찬불가" ],
["chant", "성가" ],
["ဗုဒအလှူငွေထည့်", "불전을내다" , sentence],
["ဗုဒအလှူငွေ", "불전" ],
["ခရစ်ယာန်အလှူငွေထည့်", "현금을내다" , sentence ],
["go on a pilgrimage", "성지순례를가다" , sentence ],
["disrespect/buddhism script ", "불경" ],
["bible", "성경" ],
["koran", "코란" , eng ],
["religion", "종교" ],
["event", "행사" ],
["ဖြစ်သောကြောင့်", "라서"  , sentence],
["cause/reason", "원일" ],
["wish", "소원" ],
["buddha", "부처님" ],
["suspend/hang", "매달다" ],
["define/unveil/light up", "밝히다" , derived ],
["among", "중의" , sentence ],
["Jesus", "예수님" ],
["tree", "트리" , eng ],
["easter", "부활절" ],
["resurrect", "부활하다" ],
["egg", "달걀" ],
["hen egg", "계난" ],
["each other", "서로" , sentence],
["share and eat", "나누어먹다", derived ],
["new/အသစ်ဖြစ်သော", "새로운" , derived],
["life", "생명" ],
["စတင်ခဲ့တယ်လို့ဆိုတယ်", "시작했다고합니다", grammarAndExtra ],
["ramadan", "라마단" , eng ],
["arabic", "아랍어" , derived],
["sacred", "신성하다" ],
["think", "여기다" ],
["special", "특별" ],
["moderation/abstinence", "절제" ],
["ကောင်းလာခဲ့ရင်", "좋아지셨으면"  , sentence ],
["however", "그러나" , sentence ],
["god", "하나님" ],


//26
["home use", "가정" ],
["emergency exist", "비상구" ],
["emergency medicine", "비상약" , derived],
["sympton", "증상" ],
["chemist", "약사" ],
["lastnight", "어젯밤" , derived ],
["body", "뭄" ],
["have diarrhea", "설사를하다" , sentence ],
["diarrhea", "설사" ],
["strange", "이상하다" ],
["abnormality", "이상" ],
["dairy product", "유제품" ],
["have a running nose", "콧물이나다" , sentence ],
["running nose", "콧물" ],
["have an upset stomach", "배탈이나다" , sentence ],
["upset stomach", "배탈" ],
["have an indigestion", "소화가안되다" , sentence ],
["vomit", "토하다" ],
["cut ones hand", "손을베다" , sentence ],
["mow/lop/cut", "베다" ],
["burn ones hand", "손을데다" , sentence ],
["hot", "데다" ],
["sprain ones ankle", "발목을삐다" , sentence ],
["sprain", "삐다" ],
["have a broken leg", "다리가부러지다" , sentence ],
["broken", "부러지다" ],
["bandage", "붕대" ],
["ointment", "연고" ],
["parse/အကြောကပ်", "파스" , eng],
["band/ရေစိုခံ", "밴드", eng ],
["adhestive plaster/အနာကပ်", "반창고" ],
["disinfectant", "소독약" , derived ],
["eyewash", "안약" , derived ],
["nutrients", "영양제" , derived ],
["pill", "일약" ],
["cold medicine", "감기약" , derived],
["painkiller", "진통제" ],
["fever remedy", "해열제" , derived ],
["if", "혹시" , sentence ],
["usuage", "용법" ],
["3rd time", "3회" ],
["after every meal", "매식후" ],
["2 days supply/ ", "2일분" ],
["taking", "복용" ],
["1 pouch each", "1포씩" ],


//27
["condition", "조건" ],
["treatment", "진료" ],
["medical", "의료" ],
["orthopedics/အရိုးအကြောအထူးကု", "정형외과" ],
["otorhinolaryngology/ နားနှာခေါင်းလည်ချောင်းအထူးကု", "이비인후과" ],
["dermatology/အရေပြားအထူးကု", "피부과" ],
["obstetrics and gynecology/သားဖွားမီးယပ်", "산부인과" ],
["pediatrics", "소아과" ],
["prescribe", "처방하다" , derived ],
["take a steam", "찜질을하다" , sentence ],
["ကျပ်ထုတ်ထိုးခြင်း", "찜질" ],
["operate", "수술하다" ],
["apply ointment", "연고를바르다" , sentence ],
["bandage(v)", "붕대를감다", sentence ],
["put on a cast", "깁스를하다" , sentence],
["cast(leg)", "깁스" ],
["knead", "주무르다" ],
["located", "위치한" , derived ],
["7ခုသော", "7개의", sentence ],
["korean medicine treatment", "한방진료" , derived ],
["synthesis", "종합" ],
["checkup", "검진" ],
["in case of emergency", "응급상황시" , derived ],
["english", "영어" ],
["chinese", "중국어" , derived ],
["japanese", "일분어" , derived ],
["5 languages", "5개국어" , derived ],
["break", "휴진" , derived ],
[" ", "종합검진" ], //1111111111111111111111111111111111111111111

//28
["even", "으도" ],
["atm", "인출기" ],
["finance", "금융" ],
["application paper", "신청서" , derived ],
["signature", "서명" ],
["check card", "체크카드", eng ],
["window/counter", "창구" ],
["account", "계좌" ],
["banking", "뱅킹" , eng ],
["hey", "저기요" , sentence ],
["button", "버튼" , eng ],
["deposit", "입금" ],
["withdraw", "출금" ],
["loan", "대출" ],
["account-account transfer", "계좌이체" ],
["balance", "잔액" ],
["checking", "조회" ],
["organize", "정리" ],
["custom/ကိုက်ညီသော", "맞춤" , derived ],
["increase", "늘어나다" ],
["discount", "할인" ],
["overseas", "해외" ],
["center", "중심" ],
["installation", "설치" ],
["also", "또한" , sentence ],
["online", "온라인" , eng ],
["tiring", "힘든" , derived ],
["sales", "영업" ],

//29
["postcard", "엽서" ],
["mail(thing)", "우편물" ],
["courier/delivery", "택배" ],
["international", "국제" ],
["express mail", "특급우편" ],
["scale(machine)", "저울" ],
["one or two months", "한두달" , derived ],
["ship (line)", "배편" ],
["flight (line)", "항공편" ],
["in ten days", "열흘에서" , sentence ],
["in a hurry", "급하다" ],
["put on (the scale)", "올려놓다" , derived ],
["weight", "무게" ],
["registered mail", "등기우편" ],
["international express", "국제특급" ],
["send", "발송하다" ],
["sending", "발송" ],
["delivered or not", "배달여부" , derived ],
["whether", "여부" ],
["immediately", "즉시" ],
["result", "결과" ],
["inform", "알리다" , derived ],
["want", "원하다" ],
["goods", "물품" ],
["things", "물건" ],
["substance", "물질" ],
["korean medicine", "한약" , derived ],
["animals", "동물류" ],
["plants", "식물류" ],
["explosive material/ပေါက်ကွဲလွယ်သောအရာ", "폭발성물질"  , derived ],
["combustible material/မီးလောင်အငွေ့ပျံလွယ်သောအရာ", "가연성물질" , derived ],
["explosion", "폭발" ],
["combustion", "가연" ],
["gold", "금" ],
["silver", "은" ],
["precious metals", "귀금속" ],
["such as", "등의" , sentence ],
["traveler's check", "여행자수표", derived ],
["airline ticket", "항공권" , derived ],

//30
["at all", "전혀" ],
["law", "법률" ],
["gugak/korean classical", "국악" ],
["nutrition", "영양" ],
["western medical treatment", "양방진료" , derived ],
["user", "이용자" , derived ],
["participation", "참여" ],
["experience/ကိုယ်တိုင်ပါဝင်ဆောင်ရွက်ခြင်း", "체험" ],
["volunteer", "자원봉사" ],
["bussiness owner", "사업주" ],
["public", "공공" ],
["billboards/signs", "게시판" ],
["nationwide", "전국" ],
["come true", "이루어지다" ],
["grievance", "고충" ],
["by country", "국가별" , sentence ],
["planning", "기획" ],
["planning", "계획" ],
["information board", "안내판" , derived ],
["advertisement", "광고" ],
["cricket", "귀뚜라미" ],
["square", "네모" ],
["eat while placing bowl on table", "놓고먹다" , sentence ],
["mountaineering club", "등산동호회" , derived],
["lion", "사자" ],
["shrimp", "새우" ],
["fox", "여우" ],
["directions", "방향" ],

//31
["than", "보다" ],
["air/atmosphere", "공기" ],
["comparison", "비교" ],
["admistration", "행정" ],
["city", "도시" ],
["characteristic", "특성" ],
["temperature", "기온" ],
["temperature", "온도" ],
["video/သုံညအထက်", "영상" ],
["below freezing", "영하" ],
["humidity", "습도" , derived ],
["highest", "최고" ],
["minimum/lowest", "최저" ],
["highest temperature", "최고기온", derived ],
["minimum temperature", "최저기온" , derived],
["temperature is low", "기온이낮다" , sentence],
["low", "낮다" ],
["humid", "습하다" ],
["drying", "건조" ],
["population", "인구" ],
["secluded", "한적" ],
["air is clear", "공기가맑다" , sentence ],

//32
["dog day/အပူဆုံးနေ့", "복날" ],
["cooking", "조리" ],
["recipe", "조리법" , derived],
["bean", "콩" ],
["bean noodles", "콩국수" , derived],
["red bean shaved ice", "팥빙수" ],
["red bean porridge", "팥죽" ],
["sweet potato", "고구마" ],
["roasted sweet potato", "군고구마" , derived],
["dough", "찐빵" ],
["ဆန်မုန့်", "호떡" ],
["ဆန်", "떡" ],
["sheep", "양" ],
["green onion", "파" ],
["onion", "양파" ],
["garlic", "마늘" ],
["carrot", "당근" ],
["boil(noodle)", "끓이다" ],
["boil(egg)", "삶다" ],
["life", "삶" ],
["roast/bake", "굽다" ],
["fry(few oil)", "볶다" ],
["fry(much oil)", "튀기다" ],

//31+32
["novelty", "신기" ],
["all year round", "일년내내" , derived],
["20 degrees", "20도" , derived],
["ခန့်လောက်ဖြစ်သောကြောင့်", "정도라서"  , sentence],
["beach", "바닷가" , derived],
["သိပါပြီ", "알았어요"  , sentence],
["နားလည်ပါပြီ", "알겠습니다"  , sentence],
["bottled water/ထုတ်ရေ/ရေသန့်", "생수" , derived],
["cold water", "냉수" , derived],
["hot water/random number", "난수" , derived],
["half past 2", "2시반" , derived],
["percentage/pro", "프로" ],
["free", "자유롭다" ],
["special city", "특별시" , derived],
["Metropolitan city", "광역시" ],
["state/road", "도" ],
["special self-governing city", "특별자치시" , derived],
["special autonomous province", "특별자치도" , derived],
["Metropolitan area", "수도권" , derived],
["korea/ကိုးရီးယားပြည်သူ့သမ္မတနိုင်ငံ", "대한민국"  , derived],
["half", "절반" ],
["mountainous district", "산지" , derived],
["it is a mountainous area", "산지이다", derived ],
["tourist", "관광객" , derived],
["many tourists visit", "관광객이많이찾다" , sentence],
["central", "중부" , derived],
["eastern", "동부" , derived],
["western", "서부" , derived],
["southern", "남부" , derived],
["northern", "북부" , derived],
["role", "역할" ],
["science", "과학" ],
["center/ ", "중심지" , derived],
["maximum", "최대" ],
["rice", "쌀" ],
["production", "생산" ],
["play a role", "역할을하다" , sentence],
["place of production", "생산지" , derived],
["industry", "공업" ],
["development", "발달" ],
["shilla", "신라" , eng],
["legacy", "유산" ],
["be representative", "대표적이다" ],
["be born again", "거듭나다" ],
["unique", "독특" ],
["average", "평균" ],
["annual average", "연평균" , derived],
["kite/year", "연" ],
["nature", "자연" ],
["be called", "불리다" ],
["suprise/suddenly", "깜짝" ],
["tourist destination", "관광지" , derived ],
["heat", "더위" ],
["strength", "힘" ],
["strength", "기운" ],
["no strength", "힘이없다" , sentence],
["be strong", "힘이나다" , sentence],
["beat the heat", "더위를이기다" , sentence],
["earth", "땅" ],
["sweat", "땀" ],
["at the time", "때" ],
["at this time", "이때" , derived],
["sweat", "땀을홀리다" , sentence],
["bewitched/ ", "홀리다" ],
["ginseng", "인삼" ],
["chestnut", "밤" ],
["left", "빠지다" ],
["mother", "산모" ],
["give birth", "낳다" ],
["favor/grace", "은혜" ],
["memory", "기억" ],
["each", "각자" , sentence],
["cooking oil", "식용유" ],
["moderation", "적당" ],
["separately", "따로" ],
["အဲဒါကြောင့်", "그러니까" , sentence],
["keep", "간직" ],


//33
["songpyeon", "송편" ],
["guess", "추측" ],
["han bok", "한복" , derived ],
["tokguk", "떡국" , derived ],
["နှစ်သစ်ကူးကန်တော့ခြင်း", "세배" ],
["ဆုပေးခြင်း", "덕담" ],
["နှစ်သစ်ကူးမုန့်ဖိုး", "세뱃돈" , derived ],
["yuch ကစားနည်း ", "윷놀이" , derived],
["ကစားနည်း", "놀이" ],
["ဝိညဏ်ကန်တော့ခြင်း", "차례" ],
["ဝိညဏ်ကန်တော့သည်", "차례를지내다" , sentence ],
["ကန်တော့သည်", "절하다" ],
["သချိုင်းကန်တော့ခြင်း", "성묘" ],
["လပြည့်ခြင်း", "보름달" ],
["ဆန်ဒဆုတောင်းသည်", "소원을빌다" , sentence ],
["ဆန်ဒဆုတောင်းသည်", "소원을빕니다" , sentence ],
["ဆုတောင်းသည်", "빌다" ],
["နှစ်သစ်ဖြစ်ပါတယ်", "설날이었습니다" , sentence],
["new year", "새해" ],
["luck", "복" ],
["ပထမဆုံးလပြည့်နေ့", "정월대보름" , derived ],
["first", "젓" ],
["first month", "정월" ],
["6မျိုးသော", "다섯가지" , sentence],
["ကောက်ပဲဖြင့်ချက်သော", "곡식으로지은" , sentence],
["ငါးမျိုးကောက်ပဲထမင်း", "오곡밥" ],
["မြေပဲ", "땅콩" , derived],
["walnut", "호두" ],
["shell", "껍질" ],
["hard", "딱딱하다" ],
["ဒါကို", "이를" , sentence],
["nuts/အခွံမာသီး", "견과류" ],
["nuts/အခွံမာသီး", "부럼" ],
["break", "깨다" ],
["ယားယံခြင်း", "부스럼" ],
["ကောက်ရိတ်သိမ်းပွဲ", "한가위" ],
["ကောက်ရိတ်သိမ်းပွဲ", "팔월대보름" ],
["လတ်လတ်ဆတ်ဆတ်", "갓" ],
["harvesting", "수확" ],
["ဝိုင်းကြီးပတ်ပတ်", "강강술래" ],
["under the moon", "달아래" , derived ],
["အဝိုင်းပုံဖြစ်စွာ", "동그랗게" ],
["ဖြေးဖြေး", "빙글빙글" ],
["လည်သောကစားနည်း", "도는놀이" , derived],
["holiday is short", "연휴가짧다" , sentence],
["last snow", "지난설" ],
["envy", "부럽다" ],
["upset", "속상하다" ],
["ancestor", "조상" ],

//34
["ရက်တရာပြည့်နေ့", "백일" , derived],
["1st birthday", "돌" ],
["parents' day", "어버이날" ],
["teachers' day", "스승의날" ],
["wedding anniversary", "결혼기념일" , derived],
["60 birthday", "환갑" ],
["70 birthday", "칠순" ],
["invitation letter", "청첩장" ],
["congratulatory money", "축의금" , derived ],
["groom", "신랑" ],
["bride", "신부" ],
["ဘိသိတ်ဆရာ", "주례" ],
["ဧည့်ပရိသတ်", "하객" ],
["party", "잔치" ],
["party", "피로연" ],
["ယောက်ခမကန်တော့ခြင်း", "폐백" ],
["ယောက်ခမကန်တော့သည်", "폐백을드리다" , sentence],
["ကလေးဆီကို", "아기한테/아기에께" , sentence],
["doll", "인형" ],
["အရာကတော့", "게/것은" , sentence],
["suggestion", "추천" ],
["လုပ်ပြီးတာနဲ့ချက်ချင်း", "V+고나서" , grammarAndExtra ],
["သာရေးနာရေး", "경조사" ],
["wedding", "혼례" ],
["future", "미래" ],
["modern", "현대" ],
["အခမ်းအနား", "식장" ],
["ဒါပေမယ့်", "그렇지만" , sentence ],
["is traditional", "전통적이다" , derived],
["shape", "모습" ],
["ဝိညဏ်ကန်တော့ခြင်း", "제사" ],
["be simplified", "간소화되다" ],
["sacrificial table/ ", "제사상" , derived],
["မုန့်", "전" ],
["sincere", "정성스럽다" ],
["funeral", "장례" ],
["silence(memorial)", "묵념" ],
["အခမ်းအနားပြုလုပ်သည်", "장을치르다" , sentence],
["pay", "치르다" ],
["western style", "서양식" , derived],
["wedding dress", "웨딩드레스" , eng],
["custom/ဓလေ့ထုံးစံ", "풍습" ],
["box", "함" ],
["facing", "맞선" ],
["meet and greet", "상견례" ],
["instead of a gift", "선물대신" , sentence],
["enter/", "입장하다" ],

//35
["မဟုတ်လား", "V+잖아요" ],
["ကိုးရီးယားခေတ်ရေစီးကြောင်း", "한류" ],
["economy", "경제" ],
["entertainment", "예능" ],
["performance", "공연" ],
["actor", "배우" ],
["Kpop", "케이팝" , eng],
["celebrity", "연예인" ],
["idol", "아이돌" , eng],
["electronic/former", "전자" , derived],
["new product", "신제품" , derived],
["screen", "화면" ],
["export", "수출" ],
["import", "수입" ],
["export goods", "수출품" , derived],
["developed countries", "선진국" ],
["developing countries", "개발도상국" , derived],
["trade", "무역" ],
["sirocco/ ", "열풍" ],
["number", "수" ],
["2000ပြည့်နှစ်", "2000년대" , derived],
["early", "초반" ],
["ထုတ်လွှင့်ပြသခြင်း", "발영" ],
["recent", "최근" ],
["drag", "끌다" ],
["နာမည်ကြီးနေရာ", "명소" , derived],
["specialty store/နာမည်ကြီးဆိုင်", "전문점" ],
["recall", "떠울라다" ],
["appear", "등장하다" ],
["hero/အဓိကဇာတ်ဆောင်", "주인공" ],
["course", "코스" , eng ],
["product/(travel sometimes)", "상품" ],
["fan", "팬" , eng ],
["star", "스타" , eng],
["သူတို့တွေက", "그들이" ],
["interest", "재미" ],
["interest", "관심" ],
["travel agency", "여행사" , derived],
["traveler", "여행자" , derived],
["show off", "선보이다" ],
["development", "발전" ],
["development", "개발" ],
["war", "전쟁" ],
["poor", "가난하다" ],
["by chance/ ", "우연히" ],
["fall in love", "반하다" ],
["before", "이전" ],
["simple", "단순하다" ],
["assembled product", "조립제품" , derived],
["gain", "늘다" ],
["south east asia", "공담아" , derived],
["popular culture", "대중문화" , derived],
["of course", "물론" , sentence],
["europe", "유럽" , eng],
["asia", "아시아" , eng],
["news", "소식" ],
["i heard the news", "소식들었어요" , sentence],
["effect", "영향" ],



//36.1
["costume", "복장" , derived],
["uniform", "유니폼" , eng ],
["neat", "단정하다" ],
["clean", "깔끔하다" ],
["button", "단추" ],
["button up", "단추를잠그다" , sentence],
["lock", "잠그다" ],
["unbutton", "단추를풀다" , sentence],
["zip up", "지퍼를올리다" , sentence],
["zip", "지퍼" , eng],
["unzip", "지퍼를내리다" , sentence],
["tie a tie", "넥타이를매다" , sentence],
["untie a tie", "넥타이를풀다" , sentence],
["attitude/", "태도" ],
["be polite", "예의가있다" , sentence],
["not polite", "예의가없다" , sentence],
["speak plain language", "반말을하다" , sentence],
["say honoricfics", "존댓말을하다" , sentence],
["respect", "존대" ],
["respect", "존중하다" ],
["be considerate", "배려하다" ],
["praise", "칭찬하다" ],
["do carelessly", "함부로하다" , sentence],
["carelessly", "함부" ],
["အနှောင့်ယှက်ပေးသည်", "피해를주다" , sentence],
["obstacle", "피해" ],
["uncomfortable", "불쾌하다" ],
["ignore", "무시하다" ],

//37.1
["corridor", "복도" ],
["laundry room", "세탁실" , derived],
["shower room", "샤워실" , eng],
["roommate", "룸메이트" , eng],
["concierge", "관리인" , derived],
["follow the rules", "규칙을지키다" , sentence],
["rules", "규칙" ],
["break the rules", "규칙을어기다" , sentence],
["air conditioner", "냉난방기" , derived],
["cooling", "냉방" , derived],
["heating", "난방" , derived],
["electric stove", "전기난로" , derived],
["electric pad", "전기장판" , derived],
["floor/pad", "장판" ],
["switch on", "스위치를켜다" , sentence],
["switch", "스위치" , eng ],
["switch off", "스위치를끄다" , sentence],
["plug ", "플러그" , eng],
["plug in", "플러그를꽂다" , sentence],
["unplug", "플러그를뽑다" , sentence],

//36.2 
["လက်ရှိနေရာ", "현장" ],
["leader/monitor", "반장" ],
["ပထမဆုံးဖြစ်သောကြောင့်", "처음이라" , sentence],
["familiar", "익숙" ],
["factory owner", "공장장" ],
["ဘာကိစ္စရှိလို့လဲ", "무슨일이신데요" , sentence],
["kick", "툭툭차다" , derived],
["behavior", "행동" ],
["မသိဘဲနဲ့", "모르게" , sentence],
["annoyed", "짜증이나다" ],
["အဲလိုဖြစ်ခဲ့ပါတယ်", "그랬어요" , sentence],
["milling", "밀링" , eng],
["distribution business", "유통업" ],
["product packaging", "제품포장" , derived],
["getup/ဝတ်စုံပြည့်", "옷차림" ],
["office food/ရုံးအလုပ်", "사무식" , derived],
["blue collar job", "생산직" , derived],
["working clothes", "근무복" , derived],
["jumper", "점퍼" , eng ],
["basic", "기본" ],
["basic", "기본적이다" , derived],

//37.2
["သတိထားစရာကိစ္စရပ်", "주의사항" , derived],
["dwelling type/နေထိုင်မှုပုံစံ", "주거형태" ],
["dwelling", "주거" ],
["type", "형태" ],
["outsider", "외부인" ],
["cookware", "조리기구" ],
["outing", "외출" ],
["facility", "시설" ],
["equipment", "설비" ],
["facility", "시설물" , derived],
["breaking", "파손" ],
["report", "보고" ],
["report paper", "보고서" , derived],
["immediately", "당장" ],
["ဘယ်သူမှ", "아무도" , sentence],
["its a big deal", "큰일이나다" , sentence],
["nerve", "신경" ],
["အာရုံစိုက်သည်", "신경쓰다" , sentence],
["independent", "독립적이다" ],
["building type", "빌딩형" , derived],
["public", "공동" , derived],
["housing", "주택" ],
["single", "단독" ],
["structure", "구조" ],
["high building", "건축물" , derived],
["one room", "원룸" , eng ],
["least", "최소" ],
["equipped", "갖추" ],
["dorm", "고시원" ],
["grudge/ချွေတာသည်", "아끼다" ],

//38
["superior", "상사" ],
["subordinate/load", "부하" ],
["get along badly", "사이가나쁘다" , sentence],
["encourage", "격려" ],
["help each other", "서로위해주다" , sentence],
["atmosphere(workplace)", "분위기" ],
["discipline is strict", "규율이엄격하다" , sentence],
["discipline", "규율" ],
["strictness", "엄격" ],
["hit", "때리다" ],
["swear(bad)", "욕을하다" , sentence],
["request", "요청" ],
["make angry", "화를내다" , sentence],
["fight", "싸움" ],
["brawl", "말다툼" ],
["misunderstanding", "오해" ],
["clear up misunderstanding", "오해를풀다" , sentence ],
["reconciliation", "화해" ],
["အလုပ်လုပ်ရတာကောင်းပါတယ်", "일할맛이나요" , sentence],
["conflict", "갈등" ],
["အမည်မှည့်ခေါ်ခြင်း", "호칭" ],
["solving", "해결" ],
["အချင်းချင်း", "끼리" ],
["superior", "윗사람" , derived],
["lower person", "아랫사람" , derived],
["more/တော်တော်လေး", "훨씬" ],
["things get better", "일이더잘되다" , sentence],
["in a few hours ago", "조금전에" , sentence],
["slow", "느리다" ],
["fight", "싸우다" ],
["ထွေထွေထူးထူးမဟုတ်ပါဘူး", "별일아니에요" , sentence],
["လုံးဝ", "하도" ],
["လစ်လျူရှုတယ်လို့ထင်ခဲ့ပါတယ်", "무시하는줄알았어요" , sentence],
["အခုကတော့", "이젠" , sentence],
["တော်ပါတယ်", "잘했어요" , sentence],
["repeatedly", "자꾸" ],
["supress(anger)", "참다" ],
["position(career)", "직책" ],
["position(career)", "직급" ],
["ဥပမာပေးသည်", "예를들다" , sentence],
["ဒါရိုက်တာ", "부장님" ],
["ကိုယ်စားလှယ်", "대리남" ],
["ပိုင်ရှင်", "주임님" ],
["surname", "성" ],
["personal", "개인적이다" ],
["friendliness", "친근함" ],
["admit/recognition", "인정" ],
["တဖက်သား", "상대" ],
["opponent", "상대방" , derived],
["wrong", "틀리다" ],
["exact", "정확" ],
["cause", "원인" ],
["အမြင်", "입장" ],
["values/တန်ဖိုးထားမှု", "가치관" ],
["active/တက်ကြွ", "적극적이다" ],
["passive/မတက်ကြွ", "소극적이다" ],
["opening to the public(gay)", "공개" ],
["effort", "노력" ],
["refusing", "거절" ],
["terms", "용어" ],
["numbers", "숫자" ],
["regret", "후회" ],
["relief", "다행" ],
["there is no time", "시간이따로없어요" , sentence],
["everyone", "모든사람" , derived],
["smiling face", "웃는얼굴" , derived],
["mind", "마음" ],
["have/take", "갖다" ],

//39
["attend", "참석" ],
["give a treat", "한턱내다" , sentence],
["2နေရာသွား", "2차에가다" , sentence],
["cheers(toast)", "건배" ],
["welcome/illusion", "환영" ],
["farewll", "환송" ],
["intimately acquainted", "친해지다" ],
["unity meeting", "단합대회" ],
["climbing competition", "등반대회" ],
["picnic", "야유회" ],
["athletic competition", "체육대회" ],

  
  ]