

const derived = "derived"
const eng = "eng"
const grammarAndExtra = "grammar&extra"
const sentence = "sentence"

export const four = [
//41
["hand tools", "수공구" , derived],
["pliers", "펜치" , eng ],
["nipper", "니퍼" , eng ],
["flyer", "플라이어" , eng ],
["yut/ဖောက်သည်", "뜷다" ],
["hit/beat", "두드리다" ],
["fasten", "조이다" ],
["nut", "너트" , eng ],
["wolf", "볼프" ],
["air compressor", "에어콤프레서" , eng ],
["electric welder", "전기용접기" , derived],
["gas welder", "가스용접기" , derived],
["bender", "밴딩기" , eng],
["hoist", "호이스트" , eng],
["control panel", "컨트롤판넬" , eng],
["handcar", "핸드카" , eng ],
["wire reel", "전선릴" , derived],
["press/click", "클릭하다" ],
["install", "끼우다" ],
["assembling", "조립" ],
["remove", "빼다" ],
["ချိတ်ဆွဲ ကိုင်းတပ်သည်", "달다" ],
["အံဝင်ခွင်ကျထည့်သည်", "적재하다" ],
["ညှပ်ထုတ်သည်", "오리다" ],
["ထိန်းညှိသည်", "조절하다" ],
["production", "제작" ],
["cement", "시멘트" , eng ],
["concrete", "콘크리트" , eng ],
["dig", "땅을파다" , sentence],
["formwork", "거푸집" ],
["install formwork", "거푸집을설치하다" , sentence],
["assemble the rebars", "철근을조립하다" , sentence ],
["pour", "타설하다" ],
["classify", "분류하다" ],
["stack", "쌓다" ],
["ship(v)", "출하하다" ],
["deliver", "납품하다" ],
["messed up", "엉망이다" ],
["well organized", "정리가잘되어있다" , sentence],
["smell", "냄새" ],
["smell bad", "냄새가심하다" , sentence],
["noise", "소음" ],
["pleasant", "쾌적하다" ],
["vent/လေဝင်ထွက်ကောင်းအောင်လုပ်သည်", "환기하다" ],
["waste/garbage", "폐기물" ],
["waste water", "폐수" , derived],
["waste oil", "폐유" , derived],
["manure", "분뇨" ],
["excreta", "배설물" ],
["ventilator", "환풍기" , derived],
["wheelbarrow", "일륜차" , derived],
["sack", "마대" ],
["string", "비닐끈" , derived],

["rice paddy", "논" ],
["farmhouse", "농가" ],
["orchard", "과수원" ],
["hoe", "괭이" ],
["seedling", "모종" ],
["sowing", "파종" ],
["trowel", "모종삽" , derived],
["seedbox", "파종상자" , derived],
["rake", "갈퀴" ],
["combine", "콤바인" , eng ],
["raise", "키우다" ],
["raise", "기르다" ],
["cultivate", "재배하다" ],
["reap/harvest", "거두다" ],
["catch/dig", "캐다" ],
["manure", "거름" ],
["fertilize", "비료를뿌리다" , sentence],
["sow", "씨앗을뿌리다" , sentence],
["seed", "씨앗" ],
["seed", "씨" ],

["weed", "잡초" ],
["pull the weeds", "잡초를뽑다" , sentence],
["bug", "벌레" ],
["catch bugs", "벌레를잡다" , sentence],
["pesticide", "농약을치다" , sentence],
["equipment", "도구" ],
["no matter where you look", "아무리찾아도" , sentence],
["သောကြောင့်ပါ", "V+서요" , grammarAndExtra],
["ရောင်းဝယ်ဖောက်ကားနေရာ", "거래처" ],
["newly imported", "새로들여온" , sentence],
["before", "전에" , sentence],
["used", "쓰던" , grammarAndExtra],
["soft", "부드럽다" ],
["quickly", "얼른" ],
["brace", "절곡기" ],
["binding handle", "결속핸들" ],
["crowbar", "쇠지레" ],
["pipe wrench", "파이프렌치" , eng],
["grinder", "그라인더" ],
["grinder", "연삭기" ],
["affection/စို့(တူနဲ့တွဲသုံး)", "정" ],
["vice(n)", "바이스" , eng ],
["long nose pliers", "롱노즈플라이어" , eng ],
["check", "점검하다" ],
["first of all", "우선" , sentence],
["lid", "뚜껑" ],

["wood", "목재" ],
["လုပ်ဖူးတယ်", "V+은/-ㄴ 적이있다" , grammarAndExtra],
["မလုပ်ဖူးဘူး", "V+은/-ㄴ 적이없다" , grammarAndExtra],
["handle", "손잡" , derived],
["move", "움직이다" ],
["progress/ ရှေ့ဆက်လုပ်သည်", "진행돼다" ],
["ကတ်ထူပြား", "골판지" ],
["suffice", "충분하다" ],
["certain", "확실하다" ],
["workpiece", "작업물" , derived],
["really", "정작" ],
["ထိခြင်း", "장작" ],
["rotation", "회전" ],
["low speed", "저속" , derived],
["low temperature", "저온" , derived ],
["တွင်ခုံ", "선반" ],
["အဝိုင်းပုံလည်သည်", "공회전시키다" , sentence],
["part/ပစ်စည်း", "부품" ],
["mulling", "물링" , eng ],
["bite", "물다" ],
["bitten", "물리다" ],
["light bulb", "전구" ],
["instruction", "지시" ],
["heavy equipment", "중장비" ],
["team", "팀" , eng ],
["then", "그후엔" , sentence],
["size", "크기" ], 
["by size", "크기별로" , sentence],
["ပြီးခဲ့ပြီမလား", "끝났지요" , sentence],
["letter/ ပုံးကြီး", "대자" , derived],
["middle/ ပုံးလတ် ", "중자" , derived],
["device/ ပုံးသေး", "소자" ],
["30+", "30박스밖에" , sentence],
["order sheet", "주문서" , derived ],
["is/  ဖြစ်နေတယ်", "되어있다" , sentence],
["horizontally", "수평" ],
["freight", "화물" ],
["load and carry", "실어나르다" , sentence],
["move", "이동시키다" , derived],
["rock", "암석" ],
["အစရှိတာ", "따위" ],
["excavator", "굴착기" ],
["တူးထုတ်သည်", "파내다" , derived],
["handle/manage", "처리하다" ],
["soil/ ရွှံ့", "흙" ],
["တွန်းထုတ်သည်", "밀어내다" , derived],
["compact", "다지다" ],
["harden", "굳다" ],
["ground surface", "지면" , derived],
["ညှိသည်", "고르다" ],
["flatten", "평평하게" ],
["agricultural machinery", "농기계" , derived],
["tractor", "트랙터" , eng ],
["truck/lorry", "트럭" , eng ],
["dump truck", "덤프트럭" , eng],

["pebble/  ကျောက်စလစ် ", "자갈" ],
["sand", "모래" ],
["coal", "석탄" ],
["grader", "그레이더" , eng ],
["crane/lift", "크레인" , eng ],
["remicon", "레미콘" , eng ],
["open/  လှည့်သည်(ဘိလပ်မြေကား) ", "개다" ],
["gather", "모아요다" , sentence],
["current situation", "현황" ],
["individually wrapped", "개별포장" ],
["describe", "묘사" ],
["organized", "정리정돈" , derived],
["smelly", "냄새나다" , sentence],
["otherwise", "안그러면" , sentence],
["beginning with ventilation", "환기부터해야" , sentence ],
["even one day", "하루라도" , sentence],
["သူဌေးကတော်", "사모님" ],
["ကြည့်လိုက်တာ", "보니까" , sentence],
["picky", "까다롭다" ],
["original", "본래" ],
["ဖို့/ ခြင်း", "V+기" , grammarAndExtra],
["abrogate/ ", "폐기하다" ],
["ambience/change", "주변" ],
["ambience/change", "변경" ],
["may hurt", "다칠수도있다" , sentence],
["keep/storage", "보관" ],
["distinction", "구별" ],
["rural/  လယ်ယာစိုက်ပျိုးရေး ", "농촌" ],
["take", "챙기다" ],
["hardship", "고생" ],
["လုပ်လိမ့်မှာမို့လို့", "V+을/-ㄹ 거니까" , grammarAndExtra],
["after", "지난후에" , sentence],
["လုပ်မှ/ လုပ်ရမယ်", "V+야" , grammarAndExtra],
["grow", "자라다" ],
["go home", "들어가다" , sentence],
["cereals", "곡류" ],
["barley", "보리" ],
["wheat", "밀" ],
["bean", "콩" ],
["crop", "작물" ],
["firstly", "가장먼저" , sentence],
["မွေးမြူရေးဝက်", "양돈" , derived],
["မွေးနွား", "양우" , derived],
["poultry", "양계" , derived],
["barn", "축사" ],
["feed(n)", "먹이" ],
["hay", "건초" ],
["trap/ မြုံး(ငါးဖမ်းခြင်းတောင်း)", "통발" ],
["fishlight", "집어등" , derived ],
["sheep net/ ပိုက်ဆွဲစက်", "양망기" ],

["chain", "쇠사슬" ],
["anchor", "닻" ],
["pulley", "도르래" ],
["floating net/ ", "뜰채" ],
["fishhook", "낚시바늘" , derived],
["needle bar", "바늘대" ],
["buoy", "부자" ],
["buoy", "부표" ],
["submersible pump", "수중펌프" , derived],
["water glassess", "수경" , derived],
["styro box", "스티로품상자" , eng ],
["method", "방안" ],
["become", "게되다" , sentence],
["let/ အောင်လို့လုပ်သည်", "도록하다" , sentence],
["what if", "어쩌지" , sentence],
["illegal/ မတည့်သော  ", "안맞는" , derived],
["agricultural federation", "농협중앙회" ],
["ထောက်ခံခြင်းကို", "추천하길래" , sentence],
["bulging", "불룩하다" ],
["gas(v)", "가스차다" , derived],
["veterinarian", "수의사" , derived],
["ထားရမှာဖြစ်သောကြောင့်", "놓으라니까" , sentence],
["mistake", "실수" ],
["firmly", "단단히" ],
["soul(v)/ ဆူပူကြိမ်းမောင်းသည်", "혼을내다" , sentence],
["entangled", "엉키다" ],
["on time", "제때" , sentence],
["as is/ အဲဒီလိုပဲ  ", "그대로야" , sentence],
["မဖြစ်တော့ဘူ", "안되겠다" , sentence],
["formulator", "배합기" ],
["insert", "투입하다" ],
["skid loader", "스키드로더" , eng ],
["roof", "지붕" ],
["tank", "탱크" , eng ],
["operation", "조작" ],
["fish+", "물고기" , derived],
["tidal/ သဲသောင် ", "갯벌" ],

["clam", "조개" ],
["ရေဘဝဲ", "낚지" ],
["cave/ ကမာ  ", "굴" ],
["salt field", "염전" ],
["sell", "팝니다" , sentence],
["hygiene", "위생" ],
["maintain", "유지" ],
["important", "중요" ],
["warehouse", "물류창고" , derived],
["freezer", "냉동창고" , derived],
["store", "입고" ],
["release", "출고" ],
["archive/store", "보관하다" ],
["author/store", "저작하다" ],
["cover", "덮개를덮다" , sentence ],
["maintain the temperature", "온도를유지하다" , sentence ],
["inventory", "재고" ],
["keep stock", "재고를파악하다" , sentence],
["log", "원목" ],
["cut the wood", "원목을재단하다" ],
["တိုင်းတာဖြတ်တောက်သည်", "재단하다" , derived],
["seize", "파악하다" ],
["dig a groove", "홈을파다" , sentence],
["home/groove", "홈" ],
["hole", "구멍" ],
["drill a hole", "구멍을뜷다" , sentence],
["polishling/sanding", "연마" ],
["polishling/sanding", "샌딩" , eng ],
["sand(v)", "사포질하다" , derived],
["sanding(n)", "사포질" , derived],
["အရောင်တင်သည်", "도장하다" ],
["paint", "도색하다" , derived],
["rectangle ruler", "직각자" ],
["ရေချိန်", "수평대" , derived ],
["တာဝန်ကျေသည်", "수고하다" ],

["မှားပြီးတော့", "실수로" , sentence],
["cannot be used", "못쓰게돼다" , sentence],
["လက်ကျင့်သားရသည်", "손에익다" , derived],
["know-how", "노하우" , eng ],
["male and female", "남녀" , derived],
["workers", "직장인" , derived],
["dot", "점" ],
["1st place", "1위" ],
["ထင်တဲ့အတိုင်း", "역시" , sentence],
["thanks-for/  ", "덕분" ],
["opinion", "의견 " ],
["respect", "존경" ],
["you look younger", "동안이시네요/어려보이세요" , sentence ],
["answer", "응답" , derived ],
["normally", "평상시" ],
["အခွင့်ရရင်ရသလို ", "틈틈이" ],
["after that", "그뒤를" , sentence],
["success", "성공" ],
["successful", "성공적이다" , derived ],
["လူမှု ", "인간" ],
["relationships", "인간관계" , derived],
["manufacture", "가공하다" ],
["cool", "냉방하다" , derived ],
["i heard you moved", "옮기게됐다면서요" , sentence ],
["sad", "서운하다" ],
["forget", "잊다" ],
["kind", "착하다" ],
["become strong", "힘이돼다" , sentence ],
["i will contact you", "연락할게요", sentence  ],

//48
["press machine", "프레스기계" , eng ],
["snip/ ရိုက်နှိပ်ပုံပေါ်စေသည်  ", "찍어내다" , derived ],
["sharpen/ တိုက်စားသည်  ", "갈다" ],
["cut out", "도려내다" ],
[" တိုက်စားသည် ", "깎다" ],
["finger is cut off", "손가락이잘리다" , sentence ],
["cut", "잘리다" ],
["get stuck", "끼이다" ],
["ရှသည် ", "베이다" , derived ], 
["ခြေထောက်ဖိညှပ်ခံရသည် ", "발이깔리다" , sentence],
["kill/ ညှပ်သည် ", "깔리다" ],
["stuck by glass", "유리가박히다" , sentence ],
["burned/ မီးလောင်ဒဏ်ရာရသည်  ", "화상을입다" , sentence ],
["burn(n)", "화상" ],
["ထိုးစိုက်ခံရသည် ", "박히다" ],
["ဒဏ်ရာအမာရွတ်ရသည် ", "찰과상을입다" , sentence ],
["abrasions/ ဒဏ်ရာအမာရွတ်  ", "찰과상" ],
["poisoned by gas", "가스에중독되다" , sentence ],
["addicted", "중독" ],
["corner", "모서" ],
["so much/ နဂိုမူလ ", "워낙" ],
["carelessness", "방심" ],
["focus", "집중" ],
["wandering(mind)", "딴생각" , derived ],
["လုပ်သောအပြောင်းလဲမှာ ", "하는바람에" , sentence ],
["sparks/embers", "불꽃/불씨" , derived ],
["bounce", "튀다" ],
["အေးဆေးငြိမ်နေခြင်း ", "간만" ],
["calm down", "진정시키다" ],
["collapse", "붕괴" ],
["electric shock", "감전" , derived ],
["fall (human)", "추락" ],
["fall (thing)", "낙하" ],
["leak", "누출" ],
["leak", "새다" ],
["မတော်တဆဖြစ်ချိန် ", "사고발생시" , derived ],
["emergency bell", "비상벨" , derived ],
["safety pin", "안전핀", derived ],
["မီးဘက် ", "불쪽" , sentence ],
["point toward", "향하다" ],
["handle", "손잡이" , derived ],
["strong", "강하다" ],
["move/ ညှစ်သည်  ", "움키다" ],
["digestion/ မီးငြိမ်းခြင်း  ", "소화" ],

//49
["facemask", "보안면" , derived],
["welding mask", "용접면" , derived],
["earmuffs", "귀덮개" , derived ],
["safety belt(construction)", "안전대" , derived],
["ချည်လက်အိတ် ", "목장갑" , derived ],
["hit/collision", "부딪히다" ],
["hit/collision", "충돌하다" ],
["slip", "미끄러지다" , derived ],
["pit", "구덩이" ],
["fragments", "파편" ],
["စက်မှာညှပ်သည် ", "기계에감기다" , sentence ],
["gas leaks", "가스가새다" , sentence ],
["flash/ ရုတ်တရက်မေ့ခြင်း  ", "깜빡" ],
["change shoe", "갈아신다" , derived ],
["remove the gloves", "장갑을빼다" , sentence],
["အဓိက ", "요수" ],
["light", "빛" ],
["ပျံသန်းလာသည် ","날아오다" , derived],
["fly", "날다" ],
["falling", "떨어짐" , derived],
["facial/ မျက်နှာပြင် ", "안면" ],
["chemistry", "화학" ],
["heavy thing", "중량물" ],
["sharp", "날카롭다" ],
["respiratory", "호흡기" ],
["dust", "분진" ],
["vibration/ ကြွက်သားနာခြင်း  ", "진동" ],
["full body", "전신" ],
["radiation", "방사선" ],
["therefore", "그러므로" , sentence ],

//50
["rules", "수칙" ],
["compliance", "준수" ],
["look/ သေချာစစ်ဆေးသည်  ", "살피다" ],
["pay heed to", "주의하다" ],
["repair", "보수하다" ],
["improvement", "개선" ],
["take action", "조치를취하다" , sentence],
["action", "조치" ],
["health promotion", "건강증진" , derived ],
["enhancement", "증진" ],
["take care of health", "건강을챙기다" , sentence ],
["damage health", "건강을해치다" , sentence ],
["harm", "해치다" ],
["weight", "체중" ],
["standard", "표준" ],
["cardio", "유산소" ],
["stretching", "스트레칭" , eng ],
["မျှတစွာ ", "골고로" , sentence ],
["intake", "섭취하다" ],
["cleanliness", "청결" ],
["take a break", "휴식취하다" , sentence ],
["diversion", "기분전환" ],
["flank", "옆구리" ],
["stretch", "뻗다" ],
["both hands", "양손" , derived ],
["put on a pod/ လက်ယှက်သည်  ", "깍지를끼다" ],
["pass over", "넘기다" ],
["upper body", "상체" ],
["defective thing", "불량품" ],
["auditorium", "대강당" ],
["evaluation", "평가" ],
["great/ အကောင်းဆုံး  ", "우수" ],
["picked up", "뽑히다" ],
["thoroughly", "꼼꼼히" ],
["complexion", "안색" ],
["အဲလိုလုပ်ရာက ", "그러다가" , sentence ],
["ခံတွင်းကောင်းသည် " , "입맛이좋다" , sentence ],

//51.1
["EPS", "고용허가제" , derived],
["exam", "수험" ],
["exam fee", "수험료" , derived],
["exam ticket", "수험표" , derived],
["လျှောက်လွှာကတ် ", "접수증" ],
["ID photo", "증명사진" ],
["grade card/  ", "성적표" ],
["passing", "합격" ],
["failing", "불합격" ],

//52.1
["working conditions", "근로조건" , derived],
["working term", "계약기간" , derived],
["probationary period", "수습기간" ],
["work hours", "근무시간" , derived],
["break hours", "휴게시간" , derived],
["wage", "임금" ],
["payment", "지급" ],
["payment date", "지급일" , derived ],
["payment date", "지급방법" , derived],
["bussiness information", "업무내용", derived ],
["burden/ တာဝန်ယူခြင်း  ", "부담" ],
["accommodation cost", "숙식" ],
["procedure", "절차" ],
["attend an interview", "면접을보다" , sentence ],
["bussiness owner", "사업주", derived ],
["employee", "취업자" , derived],
["sign", "사인하다" , eng ],
["work", "근무하다" ],
["workplace", "근무지" , derived],
["company name", "업체명" ],
["အလုပ်ထွက်ခြင်း ", "튀직" ],
["dismissal", "해고" ],

//53.1
["ပြည်ဝင်ခြင်း ", "입국" , derived ],
["visa", "비자/사증" ],
["expiration period", "유효기간" ],
["apply for issuance", "발급을신청하다" , sentence],
[" ပြည်ဝင်စစ်ဆေးခြင်း ", "입국심사" ],
["judge", "심사" ],
["entry prohibited", "입국이금지되다" , sentence],
["နေရာချထားသည် ", "배치되다" ],
["နေရာချထားခြင်း ", "배치" ],
["bussinessman", "사업자" , derived],
["copy", "사본" ],
["number tag", "번호표" , derived],
["fingerprint", "지문" ],

//54.1
["insurance", "보험" ],
["ထိခိုက်ဒဏ်ရာရရှိခြင်း ", "상해" ],
["industrial accident", "산재" ],
["insured/ အာမခံဝင်သည်  ", "보험에가입하다" , sentence ],
["အာမခံကြေးပေးသွင်းသည် ", "보험료를내다" , sentence ],
["paying", "납입" ],
["disease", "질병" ],
["ဒုကိတ", "장해" ],
["dead", "사망" ],
["compensation", "보상" ],
["insurance money", "보험금" , derived],
["ထုတ်ပေးခြင်း ", "환급" ], 
["ထုတ်ပေးခြင်းလက်ခံသည် ", "환급받다" , derived],
["due", "만기가되다" , sentence],
["due", "만기" ],
["destroyed", "소멸되다" ],
["claim", "청구" ],
["take insurance", "보험금을타다" , sentence ],
["bill/ တောင်းဆိုစာ  ", "청구서" , derived],
["statement", "내역서" , derived],
["certificate", "진단서" ],
["hospital bill", "병원비" ],
["nursing expenses", "요양비" ],
["care", "요양" ],
["suspension benefit", "휴업급여" ],

//55.1
["salary", "급여" ],
["specification paper", "명세서" , derived ],
["specification", "명세" ],
["normal amount(salary)", "기본급" , derived],
["actual receipt", "실수령액" ],
["meal cost", "식대" ],
["tatal amount", "총액" ],
["bonus", "상여금" ],
["severance pay/ နှစ်ပြည့်ပင်စင်  ", "퇴직금" ],
["national pension", "국민연금" , derived],
["pension", "연금" ],
["year-end settlement", "연말정산" ],
["extra pay", "수당" ],
["court", "법정" ],
["work hours", "근로시간" , derived],
["extension", "연장" ],
["nighttime", "야간" ],
["paid separately", "별도로지급하다" , sentence ],
["separate", "별도" ],
["advance payment", "가불" ],
["hourly pay", "시급" , derived],
["per day pay", "일당" ],
["minimum wage", "최저임금" , derived],
["bare hands", "맨손" , derived],
["ground", "땅바닥" , derived ],

//51.2 
["ဖြည့်စွက်ရေးသားခြင်း ", "작성" ],
["renew contract", "재계약" , derived ],
["existed", "기출" ],
["previous question", "기출문제" , derived],
["solve the problem", "문제를풀다" , sentence],
["each", "각각" ],
["mark", "점" ],
["full score", "만점" ],
["standard", "기준" ],
["grade/score", "성적" ],
["qualification", "자격" ],
["notice is sent", "공지가나다" , sentence],
["notification", "공지" ],
["local", "내국인" , derived ],
["labor shortage", "인력난" , derived],
["experience/ ရင်ဆိုင်သည်  ", "겪다" ],
["under the requirements", "요건하에" ],
["legal", "합법" ],
["legally", "합법적으로", derived ],
["job seeker", "구직자" , derived],
["အချက်အလက် ", "명보" ],
["send", "송부" ],
["standard", "표준" ],
["conclusion/ လက်မှတ်ရေးထိုးခြင်း ", "체결" ],
["pre-employment", "사전취업" , derived ],
["introduction(not about self)", "도입" ],
["sector/ အလုပ်  ", "업종" ],
["distribution", "배분" ],
["division", "구분" ],
["လူဦးရေ ", "인원" ],
["countryment/ သွေးနှော  ", "동포" ],
["re-entry", "재입국" , derived],
["စုစုပေါင်း ", "충계" ],
["selection", "선발" ],
["procedure", "과정" ],
["fairness", "공정성" ],
["transparency", "투명성" ],
["up/ အဆင့်မြင့်တင်သည်  ", "제고" ],
["အချိန်တို ", "조기" ],
["adaptation", "적응" ],
["gaze/ ဖြေဆိုသူ  ", "응시" ],
["18+", "18세이상" , derived],
["under 18", "18세이하" , derived ],
["ထောင်ကျခြင်း ", "금고형" ],
["ကိုယ်ရေးမှတ်တမ်း ", "경력이" ],
["past", "과거" ],
["eviction", "강제퇴거" ],
["departure", "출국" ],
["limit", "제한" ],
["disqualified", "결격" ],
["reason", "사유" ],
["evaluation standard", "평가기준" , derived],
["communication skill", "의사소통능력" , derived],
["communication", "소통" ],
["regard/ စပ်ဆက်သည်  ", "관하다" ],
["nasic knowledge", "기본지식" ],
["acceptance criteria", "합격기준" , derived],
["total score", "총득점" ],
["valid", "유효" ],

//52.2
["employemnt contract", "근로계약" , derived],
["curiosity", "궁금" ],
["contract", "계약서" , derived],
["as much as/ လုပ်သလောက် ", "한만큼" ],
["lucky", "운이좋다" , sentence ],
["first/ ပုံမှန် ", "일단" ],
["dispute", "분쟁" ],
["rights", "권익" ],
["protect", "보호" ],
["format", "서식" ],
["mutual", "상호" ],
["to set/ သတ်မှတ်ကြမယ်ဆိုသော ", "정하고자하는" , sentence],
["main", "주요" ],
["within 1 to 3 years", "1년에서3년이내" , sentence],
["discussion", "협의" ],
["decision", "결정" ],
["set/ အသစ်ပြန်လည်သတ်မှတ်သည်  ", "설정하다" ],
["labor standard act", "근로기준법" , derived],
["as defined", "정한대로" , sentence],
["writing(in contract)", "기재" ],
["skip", "생략" ],
["level/ အစစ်မှန်  ", "수준" ],
["climb", "오르다" ],
["apply", "적용하다" ],
["item/ ခေါင်းစဥ် ", "항목" ],
["အပိုင်းလေး ", "칸" ],
["နေထိုင်ခန်း ", "숙실" ],
["expense", "비용" ],
["အခြေနေ ", "정도" ],
["explicitly", "명시적으로" , derived],
["express", "명시" ],
["act (on behalf)", "대행하다" ],
["2စုံ(contract) ", "2부" ],

//53.2
["naughty", "야해" ],
["expected", "예정" ],
["identity", "신분" ],
["gurantee", "보장" ],
["expires", "만료되다" ],
["renewel", "갱신" ],
["over", "초과" ],
["long term", "장기" ],
["admistractive policy", "행정시책" , derived],
["initiative", "시책" ],
["reflect", "반영하다" ],
["grant", "부여" ],
["rights", "권리" ],
["under international law", "국제법상" , derived],
["lost", "상실" ],
["take/ ခံယူခြင်း(နိုင်ငံသား) ", "취득" ],
["မွေးဖွားခြင်း  ", "출행" ],
["corresponds to", "해당하다" ],
["period", "시기" ],
["change", "변경" ],
["brance office", "출장소" ],
["receipt/ စာရင်းသွင်းခြင်း ", "접수" ],
["non-specialized", "비전문" ],


["ဖြစ်တယ်လို့ထင်တယ် ", "V+는줄알다" , grammarAndExtra],
["external", "외적인" , derived],
["ကံကောင်းလို့ပေါ့ ", "다행이네요" , sentence],
["at that time", "당시" , derived], 
["eyewitness", "목격자" ],
["statement(witness)", "진술" ],
["the first", "최초" ],
["return cost", "귀국비용" ],
["payback", "체불" ],
["subject(like verb)", "주체" ],
["receipt/ ", "수령" ],
["director", "감독과" ],
["leave", "이탈" ],
["dismissed", "해지되다" ],
["lowest", "최저" ],
["", "미경" ],
["အဲဒီလိုပဲ ", "그런지" , sentence],
["အဲလိုလုပ်ပါ့မယ် ", "그럴게요" , sentence],

["be compelled", "몰리다" ],
["gathet", "모으다" ],
["female employee", "여직원" , derived],

//59.1
["familiar", "익하다" ],
["disease/illness", "병" ],
["occupational disease", "직업병" , derived],
["walk", "보행" ],
["no firearms", "화기금지" , derived],
["firearms", "화기" ],
["flammables", "인화성물질" , derived],
["ignition/combustion", "인화" ],
["oxidizing substances", "산화성물질" , derived],
["oxidation", "산화" ],
["acute toxicity", "급성독" ],
["radiation material", "방사선물질" , derived],
["radiation", "방사" ],
["high voltage electricity", "고압전기" , derived],
["high voltage/pressure", "고압" ],
["hanging object", "매달린물체" , derived],
["falling object", "낙하물" , derived],
["high temperature warning", "고온경고" , derived],
["low temperature warning", "저온경고" , derived],
["loss of balance", "몸균형상실" , derived],
["body balance", "몸균형" ],
["loss", "상실" ],
["dangerous place", "위험장소" , derived],

//55.2
["name", "성명" ],
["details", "세부" ],
["income tax", "소득세" ],
["resident tax", "주민세" , derived],
["cost", "대가" ],
["open/ အကောင့်ဖွင့်ခြင်း ", "개설"  ],
["တိကျလားဆိုတာ", "정확한지" , sentence  ],
["set", "책정되다" , derived ],
["1.5x", "1.5배" ],
["approximately", "대략" ],
["when it stops", "그만돌때" ],
["payment", "지불" ],
["very", "굉장히" ],
["pay", "납부" ],
["vacation/leave", "휴가" ],
["reference method", "기준법" ],
["မျက်နှာရိပ်ကြည့်သည် ", "눈치를보다" , sentence],
["sense", "눈치" ],
["annual", "연차" ],
["လုပ်နေဆဲပါ ", "하는중이야" , sentence],
["အကဲခတ်တော်သည်", "눈치를빠르다" , sentence ],
["apply for leave day", "휴가를신청하다" , sentence ],
["paid holiday", "유급휴일" ],
["unpaid holiday", "무급휴일" ],
["statutory holiday", "법정휴일" , derived ],
["scheduled holiday (by contract)", "약정휴일" , derived],
["annual leave", "연차휴가" , derived ],
["maternity leave", "출산휴가" ],
["အချက် ", "점" ],
["common/mutual", "공통" ],
["duty", "의무" ],
["on the other hand", "반면" ,sentence ],
["satisfy(v)", "충족" ],
["exemption", "면제" ],
["difference", "차이" ],
["preferably/ တတ်နိုင်သလောက် ", "가급적" ],
["submit", "제출" ],
["ache", "통증" ],
["due to", "인한", sentence  ],
["electrical department", "전기과" , derived ],
["attach", "첨부" ],
["defined", "규정되다" , derived ],
["article 55", "제55조" ],
["by", "의한" , sentence ],
["paid weekend", "유급주휴일" , derived ],
["enactment", "제정" ],
["convention/ ဆွေးနွေးညှိနှိုင်းခြင်း ", "협약" ],
["enforcement", "시행" ],
["labor and management", "노사당사자" ],
["menstrution leave", "생리휴가" ],
["pre and post natal leave", "산전.후휴가" ],
["founding", "창립" ],
["unpaid closed days", "휴무일" , derived ],
["summer vacation", "하계휴가" ],
["condolence vacation", "경조휴가" ],
["by", "에의거" , sentence ],
["unlike this", "이와달리" , sentence],

  ]

/*
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],
["", "" ],

*/